/* T42 VIAGGIOPERDUE HOTEL */
var HOTEL=[
  {
    "nome": "Aquila Edelweiss",
    "indirizzo": "Via Stazione 15",
    "citta": "Camigliatello Silano",
    "provincia": "CS",
    "prov": "CS",
    "regione": "Calabria",
    "nazione": "Italia",
    "luogo": "Camigliatello Silano (CS)",
    "tel": "+39 0984 578044",
    "email": "info@hotelaquilaedelweiss.com",
    "web": "https://www.hotelaquilaedelweiss.com",
    "note": "Sila 🌲",
    "mappa": "Aquila Edelweiss, Via Stazione 15, 87052, Camigliatello Silano, Italia"
  },
  {
    "nome": "Astoria",
    "indirizzo": "Bolshaya Morskaya str. 39",
    "citta": "St. Petersburg",
    "provincia": "",
    "prov": "",
    "regione": "Russia",
    "nazione": "Russia",
    "luogo": "St. Petersburg",
    "tel": "+7 (812) 494-57-92",
    "email": "",
    "web": "https://www.roccofortehotels.ru/en",
    "note": "",
    "mappa": "Astoria, Bolshaya Morskaya str. 39, 190031, St. Petersburg, Russia"
  },
  {
    "nome": "BelAmi",
    "indirizzo": "Via Roma 86",
    "citta": "Maglie",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "nazione": "Italia",
    "luogo": "Maglie (LE)",
    "tel": "+39 0836 312930",
    "email": "info@bel-ami.it",
    "web": "https://www.hotelbelami.it",
    "note": "Salento",
    "mappa": "BelAmi, Via Roma 86, 73024, Maglie, Italia"
  },
  {
    "nome": "Bellevue",
    "indirizzo": "Rue Grand Paradis 22",
    "citta": "Cogne",
    "provincia": "AO",
    "prov": "AO",
    "regione": "Valle d Aosta",
    "nazione": "Italia",
    "luogo": "Cogne (AO)",
    "tel": "+39 0165 74825",
    "email": "info@hotelbellevue.it",
    "web": "https://www.hotelbellevue.it/it/",
    "note": "Valle d’Aosta ⛰️ 🌳❤️",
    "mappa": "Bellevue, Rue Grand Paradis 22, 11012, Cogne, Italia"
  },
  {
    "nome": "Berghotel Randolins",
    "indirizzo": "Via Curtins 2",
    "citta": "Sankt Moritz",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Svizzera",
    "luogo": "Sankt Moritz (GR)",
    "tel": "+41 (0) 81 8308383",
    "email": "willkommen@randolins.ch",
    "web": "https://www.randolins.ch/it/",
    "note": "",
    "mappa": "Berghotel Randolins, Via Curtins 2, 7500, Sankt Moritz, Svizzera"
  },
  {
    "nome": "Bianca Relais",
    "indirizzo": "Via Dante Alighieri 18",
    "citta": "Oggiono",
    "provincia": "LC",
    "prov": "LC",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Oggiono (LC)",
    "tel": "+39 0341 1831110",
    "email": "reservation@biancarelais.it",
    "web": "https://biancarelais.it",
    "note": "",
    "mappa": "Bianca Relais, Via Dante Alighieri 18, 23848, Oggiono, Italia"
  },
  {
    "nome": "Bis Osteria Contemporanea",
    "indirizzo": "Via XX Settembre 50",
    "citta": "Colle di Val d'Elsa",
    "provincia": "SI",
    "prov": "SI",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Colle di Val d'Elsa (SI)",
    "tel": "",
    "email": "info@osteriabis.it",
    "web": "www.osteriabis.it",
    "note": "Locanda di charme, vista sulla campagna toscana 🌳❤️",
    "mappa": "Bis Osteria Contemporanea, Via XX Settembre 50, 53034, Colle di Val d'Elsa, Italia"
  },
  {
    "nome": "Borgo Santandrea",
    "indirizzo": "Via Giovanni Augustariccio 33",
    "citta": "Amalfi",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Amalfi (SA)",
    "tel": "+39 089 831148",
    "email": "info@borgosantandrea.it",
    "web": "https://borgosantandrea.it",
    "note": "",
    "mappa": "Borgo Santandrea, Via Giovanni Augustariccio 33, 84011, Amalfi, Italia"
  },
  {
    "nome": "Borgo Santo Pietro",
    "indirizzo": "Località Palazzetto",
    "citta": "Chiusdino",
    "provincia": "SI",
    "prov": "SI",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Chiusdino (SI)",
    "tel": "+30 0577751222",
    "email": "laura@borgosantopietro.com",
    "web": "https://www.borgosantopietro.com",
    "note": "",
    "mappa": "Borgo Santo Pietro, Località Palazzetto, 53012, Chiusdino, Italia"
  },
  {
    "nome": "Bulgari Milano",
    "indirizzo": "Via Privata Fratelli Gabba 7b",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Milano (MI)",
    "tel": "+39028058051",
    "email": "milano@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/milan/",
    "note": "Albergo contemporaneo in un parco 🌳❤️",
    "mappa": "Bulgari Milano, Via Privata Fratelli Gabba 7b, 20121, Milano, Italia"
  },
  {
    "nome": "Bulgari Pechino",
    "indirizzo": "No.8 Xinyuan South Road\\, Chaoyang District",
    "citta": "Beijing",
    "provincia": "",
    "prov": "",
    "regione": "China",
    "nazione": "China",
    "luogo": "Beijing",
    "tel": "+86 10 8555 8555",
    "email": "beijing@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/beijing",
    "note": "",
    "mappa": "Bulgari Pechino, No.8 Xinyuan South Road\\, Chaoyang District, 100027, Beijing, China"
  },
  {
    "nome": "Bulgari Roma",
    "indirizzo": "Piazza Augusto Imperatore 10",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Roma (RM)",
    "tel": "+39 06 36080 400",
    "email": "roma@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/rome",
    "note": "",
    "mappa": "Bulgari Roma, Piazza Augusto Imperatore 10, 00186, Roma, Italia"
  },
  {
    "nome": "Capricorno",
    "indirizzo": "Via Case Sparse 21",
    "citta": "Sauze D'Oulx",
    "provincia": "TO",
    "prov": "TO",
    "regione": "Piemonte",
    "nazione": "Italia",
    "luogo": "Sauze D'Oulx (TO)",
    "tel": "+39 0122 850273",
    "email": "info@chaletilcapricorno.it",
    "web": "https://chaletilcapricorno.it",
    "note": "Montagna 🌲❤️",
    "mappa": "Capricorno, Via Case Sparse 21, 10050, Sauze D'Oulx, Italia"
  },
  {
    "nome": "Caruso",
    "indirizzo": "Piazza San Giovanni Del Toro 2",
    "citta": "Ravello",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Ravello (SA)",
    "tel": "+39 089 858801",
    "email": "",
    "web": "https://www.belmond.com/it/hotels/europe/italy/amalfi-c",
    "note": "",
    "mappa": "Caruso, Piazza San Giovanni Del Toro 2, 84010, Ravello, Italia"
  },
  {
    "nome": "Casa Fantini",
    "indirizzo": "Piazza Motta angolo Via Roma 2",
    "citta": "Pella",
    "provincia": "NO",
    "prov": "NO",
    "regione": "Piemonte",
    "nazione": "Italia",
    "luogo": "Pella (NO)",
    "tel": "+39 0322 969893",
    "email": "info@casafantinilaketime.com",
    "web": "https://www.casafantinilaketime.com/it",
    "note": "Hotel di charme sul Lago d’Orta 🌳❤️",
    "mappa": "Casa Fantini, Piazza Motta angolo Via Roma 2, 28010, Pella, Italia"
  },
  {
    "nome": "Chalet del Sogno",
    "indirizzo": "Via Spinale 37b",
    "citta": "Madonna di Campiglio",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "nazione": "Italia",
    "luogo": "Madonna di Campiglio (TN)",
    "tel": "+39 0465 441033",
    "email": "direzione@hotelchaletdelsogno.com",
    "web": "https://www.hotelchaletdelsognocampiglio.com",
    "note": "",
    "mappa": "Chalet del Sogno, Via Spinale 37b, 38086, Madonna di Campiglio, Italia"
  },
  {
    "nome": "Ciasa Salares",
    "indirizzo": "Strada Pre de Vì 31",
    "citta": "San Cassiano in Badia",
    "provincia": "BZ",
    "prov": "BZ",
    "regione": "Trentino-Alto Adige",
    "nazione": "Italia",
    "luogo": "San Cassiano in Badia (BZ)",
    "tel": "+39 0471 849445",
    "email": "info@ciasasalares.it",
    "web": "https://www.ciasasalares.it",
    "note": "Albergo di montagna, vista sui monti 🌳❤️",
    "mappa": "Ciasa Salares, Strada Pre de Vì 31, 39036, San Cassiano in Badia, Italia"
  },
  {
    "nome": "Cipriani",
    "indirizzo": "Giudecca 10",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Venezia (VE)",
    "tel": "+39 0185 2353451",
    "email": "",
    "web": "https://www.belmond.com/it/hotels/europe/italy/venice/belmond-hotel-cipriani/",
    "note": "",
    "mappa": "Cipriani, Giudecca 10, 30133, Venezia, Italia"
  },
  {
    "nome": "Claudio Le Terrazze",
    "indirizzo": "Via XXV Aprile 37",
    "citta": "Bergeggi",
    "provincia": "SV",
    "prov": "SV",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Bergeggi (SV)",
    "tel": "+39 019 859750",
    "email": "info@hotelclaudio.it",
    "web": "https://www.hotelclaudio.it",
    "note": "",
    "mappa": "Claudio Le Terrazze, Via XXV Aprile 37, 17028, Bergeggi, Italia"
  },
  {
    "nome": "Connaught Hotel",
    "indirizzo": "Carlos Place Mayfair",
    "citta": "London",
    "provincia": "",
    "prov": "",
    "regione": "United Kingdom",
    "nazione": "United Kingdom",
    "luogo": "London",
    "tel": "",
    "email": "",
    "web": "httpS://www.maybourne.com/en/hotels/the-connaught",
    "note": "",
    "mappa": "Connaught Hotel, Carlos Place Mayfair, W1K 2AL, London, United Kingdom"
  },
  {
    "nome": "Du Clos",
    "indirizzo": "55 Chemin des Écoles",
    "citta": "Le Rouret",
    "provincia": "",
    "prov": "",
    "regione": "France",
    "nazione": "France",
    "luogo": "Le Rouret",
    "tel": "+33 (0) 4 93 40 78 85",
    "email": "contact@hotel-du-clos.com",
    "web": "https://hotel-du-clos.com",
    "note": "",
    "mappa": "Du Clos, 55 Chemin des Écoles, 06650, Le Rouret, France"
  },
  {
    "nome": "Eco del Mare",
    "indirizzo": "Località Maramozza 4",
    "citta": "Lerici",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Lerici (SP)",
    "tel": "+39 0187 964239",
    "email": "info@ecodelmare.it",
    "web": "https://ecodelmare.it",
    "note": "🌳🌅♥️",
    "mappa": "Eco del Mare, Località Maramozza 4, 19032, Lerici, Italia"
  },
  {
    "nome": "Eden",
    "indirizzo": "Località Sistiana 42",
    "citta": "Duino Aurisina",
    "provincia": "TS",
    "prov": "TS",
    "regione": "Friuli-Venezia Giulia",
    "nazione": "Italia",
    "luogo": "Duino Aurisina (TS)",
    "tel": "+39 040 2907042",
    "email": "info@edensistiana.it",
    "web": "https://www.edensistiana.it",
    "note": "",
    "mappa": "Eden, Località Sistiana 42, 3401, Duino Aurisina, Italia"
  },
  {
    "nome": "Eden",
    "indirizzo": "Via Ludovisi 49",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Roma (RM)",
    "tel": "+39 06 478121",
    "email": "",
    "web": "https://www.dorchestercollection.com/it/rome/hotel-eden",
    "note": "",
    "mappa": "Eden, Via Ludovisi 49, 00187, Roma, Italia"
  },
  {
    "nome": "Eveline Portosole",
    "indirizzo": "Corso Cavallotti 111",
    "citta": "San Remo",
    "provincia": "IM",
    "prov": "IM",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "San Remo (IM)",
    "tel": "+39 0184 503430",
    "email": "mailto:hotel@evelineportosole.com",
    "web": "https://www.evelineportosole.com",
    "note": "",
    "mappa": "Eveline Portosole, Corso Cavallotti 111, 18038, San Remo, Italia"
  },
  {
    "nome": "Four Seasons Bangkok",
    "indirizzo": "300 Charoen Krung Road, Sathorn",
    "citta": "Bangkok",
    "provincia": "",
    "prov": "",
    "regione": "Thailand",
    "nazione": "Thailand",
    "luogo": "Bangkok",
    "tel": "+66 (0) 2 032 0887",
    "email": "reservations.bangkok@fourseasons.com",
    "web": "www.fourseasons.com/bangkok",
    "note": "",
    "mappa": "Four Seasons Bangkok, 300 Charoen Krung Road, Sathorn, 10120, Bangkok, Thailand"
  },
  {
    "nome": "Four Seasons Geneva",
    "indirizzo": "33 Quai des Bergues",
    "citta": "Geneva",
    "provincia": "GE",
    "prov": "GE",
    "regione": "Liguria",
    "nazione": "Svizzera",
    "luogo": "Geneva (GE)",
    "tel": "",
    "email": "",
    "web": "https://www.fourseasons.com/geneva",
    "note": "",
    "mappa": "Four Seasons Geneva, 33 Quai des Bergues, 1211, Geneva, Svizzera"
  },
  {
    "nome": "Four Seasons Milano",
    "indirizzo": "Via Gesù 6/8",
    "citta": "Milano",
    "provincia": "Mi",
    "prov": "Mi",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Milano (Mi)",
    "tel": "+39 02 77088",
    "email": "",
    "web": "www.fourseasons.com/milan",
    "note": "",
    "mappa": "Four Seasons Milano, Via Gesù 6/8, 20121, Milano, Italia"
  },
  {
    "nome": "Grand Hotel della Posta",
    "indirizzo": "Piazza Garibaldi 19",
    "citta": "Sondrio",
    "provincia": "",
    "prov": "",
    "regione": "Italia",
    "nazione": "Italia",
    "luogo": "Sondrio",
    "tel": "+39 0342 200397",
    "email": "info@grandhoteldellaposta.eu",
    "web": "https://www.grandhoteldellaposta.eu",
    "note": "",
    "mappa": "Grand Hotel della Posta, Piazza Garibaldi 19, 23100, Sondrio, Italia"
  },
  {
    "nome": "Grand Hotel Tremezzo",
    "indirizzo": "Via Regina 8",
    "citta": "Tremezzina",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Tremezzina (CO)",
    "tel": "+39 0344 42491",
    "email": "",
    "web": "https://www.grandhoteltremezzo.com",
    "note": "",
    "mappa": "Grand Hotel Tremezzo, Via Regina 8, 22016, Tremezzina, Italia"
  },
  {
    "nome": "Grand Hotel Villa Serbelloni",
    "indirizzo": "Via Roma 1",
    "citta": "Bellagio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Bellagio (CO)",
    "tel": "+39 031 950216",
    "email": "info@villaserbelloni.com",
    "web": "https://www.villaserbelloni.com",
    "note": "",
    "mappa": "Grand Hotel Villa Serbelloni, Via Roma 1, 22021, Bellagio, Italia"
  },
  {
    "nome": "Gritti Palace",
    "indirizzo": "Campo Santa Maria del Giglio 2467",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Venezia (VE)",
    "tel": "+39 041 794611",
    "email": "",
    "web": "https://www.marriott.com/en-us/hotels/vcegl-the-gritti-palace-a-luxury-collection-hotel-venice/overview/",
    "note": "",
    "mappa": "Gritti Palace, Campo Santa Maria del Giglio 2467, 30124, Venezia, Italia"
  },
  {
    "nome": "Heart of Trento",
    "indirizzo": "Vicolo del Vò 27 Interno 24-23",
    "citta": "Trento",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "nazione": "Italia",
    "luogo": "Trento (TN)",
    "tel": "",
    "email": "trento.loftrooms@gmail.com",
    "web": "https://trentoloftroom.it",
    "note": "",
    "mappa": "Heart of Trento, Vicolo del Vò 27 Interno 24-23, 38122, Trento, Italia"
  },
  {
    "nome": "Helvetia & Bristol",
    "indirizzo": "Via dei Pescioni 2",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Firenze (FI)",
    "tel": "+3905526651",
    "email": "",
    "web": "https://collezione.starhotels.com/it/i-nostri-hotel/hel",
    "note": "",
    "mappa": "Helvetia & Bristol, Via dei Pescioni 2, 50123, Firenze, Italia"
  },
  {
    "nome": "Carlton",
    "indirizzo": "Via Senato 7",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Milano (MI)",
    "tel": "+39 02 811221",
    "email": "reservations.carlton@roccofortehotels.com",
    "web": "https://www.roccofortehotels.com/it/hotels-and-resorts/the-carlton-milan/",
    "note": "",
    "mappa": "Carlton, Via Senato 7, 20121, Milano, Italia"
  },
  {
    "nome": "Caruso",
    "indirizzo": "Piazza San Giovanni Del Toro 2",
    "citta": "Ravello",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Ravello (SA)",
    "tel": "+39 089 858801",
    "email": "",
    "web": "https://www.belmond.com/it/hotels/europe/italy/amalfi-coast/belmond-hotel-caruso/",
    "note": "",
    "mappa": "Caruso, Piazza San Giovanni Del Toro 2, 84010, Ravello, Italia"
  },
  {
    "nome": "Hotel Casa Angelina",
    "indirizzo": "Via Capriglione 147",
    "citta": "Praiano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Praiano (SA)",
    "tel": "+39 089 8131333",
    "email": "reservation@casangelina.com",
    "web": "https://www.casangelina.com",
    "note": "",
    "mappa": "Hotel Casa Angelina, Via Capriglione 147, 84010, Praiano, Italia"
  },
  {
    "nome": "Il Pellicano",
    "indirizzo": "Località Sbarcatello",
    "citta": "Porto Ercole",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Porto Ercole (GR)",
    "tel": "+39 0564 858111",
    "email": "reservations@pellicanohotels.com",
    "web": "https://www.pellicanohotelshttps://www.pellicanohotels.com/it/hotels/hotel-il-pellicano/.com",
    "note": "Camere vista mare 🌳🌅🏖️❤️",
    "mappa": "Il Pellicano, Località Sbarcatello, 58019, Porto Ercole, Italia"
  },
  {
    "nome": "Hotellerie de Mascognaz",
    "indirizzo": "Via Dondeynaz 12",
    "citta": "Ayas",
    "provincia": "AO",
    "prov": "AO",
    "regione": "Valle d Aosta",
    "nazione": "Italia",
    "luogo": "Ayas (AO)",
    "tel": "",
    "email": "info@hotelleriedemascognaz.com",
    "web": "https://www.hotelleriedemascognaz.com",
    "note": "Montagna, vista, isolato, ameno",
    "mappa": "Hotellerie de Mascognaz, Via Dondeynaz 12, 11020, Ayas, Italia"
  },
  {
    "nome": "Il Borro",
    "indirizzo": "Località Il Borro 1",
    "citta": "San Giustino Valdarno",
    "provincia": "AR",
    "prov": "AR",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "San Giustino Valdarno (AR)",
    "tel": "+39 055 977053",
    "email": "ilborro@ilborro.it",
    "web": "https://www.ilborro.it",
    "note": "🌳🌅♥️",
    "mappa": "Il Borro, Località Il Borro 1, 52024, San Giustino Valdarno, Italia"
  },
  {
    "nome": "Il Gatto Bianco",
    "indirizzo": "Viale Appennini 3",
    "citta": "Pescocostanzo",
    "provincia": "AQ",
    "prov": "AQ",
    "regione": "Abruzzo",
    "nazione": "Italia",
    "luogo": "Pescocostanzo (AQ)",
    "tel": "+39 0864 641651",
    "email": "info@ilgattobianco.it",
    "web": "https://www.ilgattobianco.com",
    "note": "Montagna ❤️",
    "mappa": "Il Gatto Bianco, Viale Appennini 3, 67033, Pescocostanzo, Italia"
  },
  {
    "nome": "Il Villino",
    "indirizzo": "Via Costantino Ruggeri 48",
    "citta": "Sant’Arcangelo di Romagna",
    "provincia": "RN",
    "prov": "RN",
    "regione": "Emilia-Romagna",
    "nazione": "Italia",
    "luogo": "Sant’Arcangelo di Romagna (RN)",
    "tel": "+39 0541 685959",
    "email": "info@hotelilvillino.it",
    "web": "https://www.hotelilvillino.it",
    "note": "🌳❤️",
    "mappa": "Il Villino, Via Costantino Ruggeri 48, 47822, Sant’Arcangelo di Romagna, Italia"
  },
  {
    "nome": "Kronenhof",
    "indirizzo": "Via Maistra",
    "citta": "Pontresina",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Svizzera",
    "luogo": "Pontresina (GR)",
    "tel": "+41 (0) 81 830 32 23",
    "email": "info@kronenhof.com",
    "web": "https://www.kronenhof.com",
    "note": "",
    "mappa": "Kronenhof, Via Maistra, 7504, Pontresina, Svizzera"
  },
  {
    "nome": "Kuerbishof",
    "indirizzo": "Via Guggal 23",
    "citta": "Anterivo",
    "provincia": "BZ",
    "prov": "BZ",
    "regione": "Trentino-Alto Adige",
    "nazione": "Italia",
    "luogo": "Anterivo (BZ)",
    "tel": "+39 0471 882140",
    "email": "info@kuerbishof.it",
    "web": "www.kuerbishof.it",
    "note": "",
    "mappa": "Kuerbishof, Via Guggal 23, 39040, Anterivo, Italia"
  },
  {
    "nome": "Kyrimai",
    "indirizzo": "Mani, Peliponnese",
    "citta": "Gerolimenas",
    "provincia": "",
    "prov": "",
    "regione": "Grecia",
    "nazione": "Grecia",
    "luogo": "Gerolimenas",
    "tel": "(+30) 27330 54288",
    "email": "info@kyrimai.gr",
    "web": "https://www.kyrimai.gr",
    "note": "Mani",
    "mappa": "Kyrimai, Mani, Peliponnese, Gerolimenas, Grecia"
  },
  {
    "nome": "L’Agnata",
    "indirizzo": "Località l’Agnata San Bachisio",
    "citta": "Tempio Pausania",
    "provincia": "SS",
    "prov": "SS",
    "regione": "Sardegna",
    "nazione": "Italia",
    "luogo": "Tempio Pausania (SS)",
    "tel": "+39 079 671384",
    "email": "info@agnata.com",
    "web": "https://www.agnata.com",
    "note": "Gallura ❤️",
    "mappa": "L’Agnata, Località l’Agnata San Bachisio, 07029, Tempio Pausania, Italia"
  },
  {
    "nome": "L’Albereta",
    "indirizzo": "Via Vittorio Emanuele 40",
    "citta": "Erbusco",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Erbusco (BS)",
    "tel": "+390307760550",
    "email": "info@albereta.it",
    "web": "https://www.albereta.it",
    "note": "",
    "mappa": "L’Albereta, Via Vittorio Emanuele 40, 25030, Erbusco, Italia"
  },
  {
    "nome": "La Conca del Sogno",
    "indirizzo": "Via San Marciano 9",
    "citta": "Nerano",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Nerano (NA)",
    "tel": "+39 081 8081036",
    "email": "info@concadelsogno.it",
    "web": "https://www.concadelsogno.it",
    "note": "",
    "mappa": "La Conca del Sogno, Via San Marciano 9, 80061, Nerano, Italia"
  },
  {
    "nome": "La Francesca",
    "indirizzo": "Via Gloria Bortolotti De Poli 8",
    "citta": "Scario",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Scario (SA)",
    "tel": "+39 0974 986068",
    "email": "info@lafrancescasud.it",
    "web": "https://lafrancescascario.it",
    "note": "Casa Blu: ospitalità in vecchie case con vista sul mare",
    "mappa": "La Francesca, Via Gloria Bortolotti De Poli 8, 84070, Scario, Italia"
  },
  {
    "nome": "La Gioiosa",
    "indirizzo": "Via Manie 55",
    "citta": "Finale Ligure",
    "provincia": "SV",
    "prov": "SV",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Finale Ligure (SV)",
    "tel": "+39 019 601306",
    "email": "",
    "web": "https://www.lagioiosahotel.it",
    "note": "6,5 km dall’uscita A10 Finale Ligure 🌳🌅",
    "mappa": "La Gioiosa, Via Manie 55, 17024, Finale Ligure, Italia"
  },
  {
    "nome": "La Parisienne",
    "indirizzo": "Via Enrico Mattei, 28",
    "citta": "Senigallia",
    "provincia": "AN",
    "prov": "AN",
    "regione": "Marche",
    "nazione": "Italia",
    "luogo": "Senigallia (AN)",
    "tel": "+39 071 6610052",
    "email": "",
    "web": "https://www.bblaparisienne.it/",
    "note": "",
    "mappa": "La Parisienne, Via Enrico Mattei, 28, 60019, Senigallia, Italia"
  },
  {
    "nome": "La Quinta Miraflores",
    "indirizzo": "844 Avenida 28 de julio",
    "citta": "Miraflores, Lima",
    "provincia": "",
    "prov": "",
    "regione": "Perù",
    "nazione": "Perù",
    "luogo": "Miraflores, Lima",
    "tel": "+51 995 938 000",
    "email": "b.hotel@quintamiraflores.com",
    "web": "https://www.quintamiraflores.com",
    "note": "",
    "mappa": "La Quinta Miraflores, 844 Avenida 28 de julio, Miraflores, Lima, Perù"
  },
  {
    "nome": "La Raia",
    "indirizzo": "Località Lomellina 26",
    "citta": "Gavi",
    "provincia": "AL",
    "prov": "AL",
    "regione": "Piemonte",
    "nazione": "Italia",
    "luogo": "Gavi (AL)",
    "tel": "+39 0143 642860",
    "email": "locanda@la-raia.it",
    "web": "https://www.la-raia.it/it",
    "note": "Colli di Gavi 🌳",
    "mappa": "La Raia, Località Lomellina 26, 15066, Gavi, Italia"
  },
  {
    "nome": "La Roccia",
    "indirizzo": "Via Litoranea Tricase",
    "citta": "Castro",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "nazione": "Italia",
    "luogo": "Castro (LE)",
    "tel": "+39 0836 979013",
    "email": "info@larocciahotel.it",
    "web": "https://larocciahotel.it",
    "note": "Camere vista mare 🌳🌅🏖️",
    "mappa": "La Roccia, Via Litoranea Tricase, 73030, Castro, Italia"
  },
  {
    "nome": "La Soglina",
    "indirizzo": "Via Carnella 6",
    "citta": "Soglio",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Svizzera",
    "luogo": "Soglio (GR)",
    "tel": "+41 81 822 16 08",
    "email": "info@lasoglina.ch",
    "web": "https://www.lasoglina.ch",
    "note": "Val Bregaglia",
    "mappa": "La Soglina, Via Carnella 6, 7610, Soglio, Svizzera"
  },
  {
    "nome": "La Sommità Relais",
    "indirizzo": "Via Scipione Petrarolo 7",
    "citta": "Ostuni",
    "provincia": "BR",
    "prov": "BR",
    "regione": "Puglia",
    "nazione": "Italia",
    "luogo": "Ostuni (BR)",
    "tel": "+39 0831 305925",
    "email": "info@lasommita.it",
    "web": "https://www.lasommita.it",
    "note": "",
    "mappa": "La Sommità Relais, Via Scipione Petrarolo 7, 72017, Ostuni, Italia"
  },
  {
    "nome": "Le Bristol",
    "indirizzo": "112 rue Di Faubourg Saint-Honoré",
    "citta": "Paris",
    "provincia": "FR",
    "prov": "FR",
    "regione": "Lazio",
    "nazione": "Francia",
    "luogo": "Paris (FR)",
    "tel": "+33 1 53 43 43 00",
    "email": "reservations.lebristolparis@oetkerhotels.com",
    "web": "https://www.oetkerhotels.com/hotels/le-bristol-paris/",
    "note": "",
    "mappa": "Le Bristol, 112 rue Di Faubourg Saint-Honoré, 75008, Paris, Francia"
  },
  {
    "nome": "Le Comptoir du Relais Saint Germain",
    "indirizzo": "9, Carrefour de l'Odéon",
    "citta": "Paris",
    "provincia": "FR",
    "prov": "FR",
    "regione": "Lazio",
    "nazione": "Francia",
    "luogo": "Paris (FR)",
    "tel": "+33 1 44 27 07 97",
    "email": "hotel@le-relais-saint-germain.com",
    "web": "https://www.hotel-paris-relais-saint-germain.com/en/",
    "note": "",
    "mappa": "Le Comptoir du Relais Saint Germain, 9, Carrefour de l'Odéon, 75006, Paris, Francia"
  },
  {
    "nome": "Les Trois Rois",
    "indirizzo": "Blumenrain 8",
    "citta": "Basel",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Lombardia",
    "nazione": "Svizzera",
    "luogo": "Basel (BS)",
    "tel": "+41 79 756 36 24",
    "email": "asseghid.dinberu spirithotels.com",
    "web": "https://www.lestroisrois.com",
    "note": "",
    "mappa": "Les Trois Rois, Blumenrain 8, 4001, Basel, Svizzera"
  },
  {
    "nome": "Locanda dell'Angelo",
    "indirizzo": "Viale XXV Aprile 60",
    "citta": "Ameglia",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Ameglia (SP)",
    "tel": "",
    "email": "info@paracucchilocanda.it",
    "web": "https://www.paracucchilocanda.it",
    "note": "",
    "mappa": "Locanda dell'Angelo, Viale XXV Aprile 60, 19031, Ameglia, Italia"
  },
  {
    "nome": "Locanda Romantica Pucci",
    "indirizzo": "Piazza Cavour 1",
    "citta": "Bagnoregio",
    "provincia": "VT",
    "prov": "VT",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Bagnoregio (VT)",
    "tel": "+39 0761 792121",
    "email": "info@hotelromanticapucci.it",
    "web": "https://www.hotelromanticapucci.it",
    "note": "❤️",
    "mappa": "Locanda Romantica Pucci, Piazza Cavour 1, 01022, Bagnoregio, Italia"
  },
  {
    "nome": "La Lampara",
    "indirizzo": "Via Tramonti 4",
    "citta": "Campiglia",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Campiglia (SP)",
    "tel": "",
    "email": "liviacerliani96@gmail.com",
    "web": "https://lalamparacampiglia.com/pages/camere",
    "note": "",
    "mappa": "La Lampara, Via Tramonti 4, 19132, Campiglia, Italia"
  },
  {
    "nome": "Maison La Minervetta",
    "indirizzo": "Via Capo 25",
    "citta": "Sorrento",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Sorrento (NA)",
    "tel": "+39 081 8774455",
    "email": "info@laminervetta.com",
    "web": "https://www.laminervetta.com",
    "note": "❤️",
    "mappa": "Maison La Minervetta, Via Capo 25, 80067, Sorrento, Italia"
  },
  {
    "nome": "Mandarin Oriental Hyde Park",
    "indirizzo": "66 Knightsbridge",
    "citta": "London",
    "provincia": "GB",
    "prov": "GB",
    "regione": "Regno Unito",
    "nazione": "United Kingdom",
    "luogo": "London (GB)",
    "tel": "+44 (0) 20 7235 2000",
    "email": "molon-reservations@mohg.com",
    "web": "https://www.mandarinoriental.com/en/london/hyde-park/stay",
    "note": "🌳♥️",
    "mappa": "Mandarin Oriental Hyde Park, 66 Knightsbridge, SW1X 7LA, London, United Kingdom"
  },
  {
    "nome": "Mandarin Oriental Lago di Como",
    "indirizzo": "Via Enrico Caronti 69",
    "citta": "Blevio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Blevio (CO)",
    "tel": "+39 031 32511",
    "email": "",
    "web": "https://www.mandarinoriental.com/lake-como/blevio/luxur",
    "note": "Camere vista lago 🌳🌅🏖️",
    "mappa": "Mandarin Oriental Lago di Como, Via Enrico Caronti 69, 22020, Blevio, Italia"
  },
  {
    "nome": "Marulivo",
    "indirizzo": "Via Castello",
    "citta": "Pisciotta",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Pisciotta (SA)",
    "tel": "0974973792",
    "email": "",
    "web": "https://www.marulivohotel.it",
    "note": "",
    "mappa": "Marulivo, Via Castello, 84066, Pisciotta, Italia"
  },
  {
    "nome": "Mezzatorre",
    "indirizzo": "Via Mezzatorre 23",
    "citta": "Ischia",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Ischia (NA)",
    "tel": "+39 081 986111",
    "email": "reservations@pellicanohotels.com",
    "web": "https://www.pellicanohotels.com/en/hotels/mezzatorre-hotel-e-thermal-spa/",
    "note": "",
    "mappa": "Mezzatorre, Via Mezzatorre 23, 80075, Ischia, Italia"
  },
  {
    "nome": "Miralago",
    "indirizzo": "Miralago 10",
    "citta": "Miralago",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Svizzera",
    "luogo": "Miralago (GR)",
    "tel": "+41 81 839 20 00",
    "email": "info@albergomiralago.ch",
    "web": "https://www.albergomiralago.ch",
    "note": "Camere vista lago 🌳🌅",
    "mappa": "Miralago, Miralago 10, 7743, Miralago, Svizzera"
  },
  {
    "nome": "Mont Cervin Palace",
    "indirizzo": "Bahnhofstrasse 31",
    "citta": "Zermatt",
    "provincia": "VS",
    "prov": "VS",
    "regione": "Sardegna",
    "nazione": "Svizzera",
    "luogo": "Zermatt (VS)",
    "tel": "+41 27 966 88 88",
    "email": "a.gartmann@seilerhotels.ch",
    "web": "https://www.montcervin.ch",
    "note": "",
    "mappa": "Mont Cervin Palace, Bahnhofstrasse 31, 3920, Zermatt, Svizzera"
  },
  {
    "nome": "Mosella Suite",
    "indirizzo": "Via San Felice 3",
    "citta": "Sottomarina di Chioggia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Sottomarina di Chioggia (VE)",
    "tel": "+39 041 0986095",
    "email": "info@mosellasuitehotel.it",
    "web": "https://www.mosellasuitehotel.it",
    "note": "",
    "mappa": "Mosella Suite, Via San Felice 3, 30015, Sottomarina di Chioggia, Italia"
  },
  {
    "nome": "Palazzo Jannuzzi",
    "indirizzo": "Vico San Aniello 39",
    "citta": "Sorrento",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Sorrento (NA)",
    "tel": "(+39) 081 8772862",
    "email": "info@palazzojannuzzi.com",
    "web": "https://www.palazzojannuzzi.com",
    "note": "",
    "mappa": "Palazzo Jannuzzi, Vico San Aniello 39, 80067, Sorrento, Italia"
  },
  {
    "nome": "Pardini's Hermitage",
    "indirizzo": "Cala degli Alberi",
    "citta": "Isola del Giglio",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Isola del Giglio (GR)",
    "tel": "+39 0564 809034",
    "email": "info@hermit.it",
    "web": "https://www.hermit.it",
    "note": "",
    "mappa": "Pardini's Hermitage, Cala degli Alberi, 58012, Isola del Giglio, Italia"
  },
  {
    "nome": "Park Villa Grazioli",
    "indirizzo": "Via Umberto Pavoni 19",
    "citta": "Grottaferrata",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Grottaferrata (RM)",
    "tel": "+3906945400",
    "email": "info@villa-grazioli.it",
    "web": "https://www.villa-grazioli.it",
    "note": "",
    "mappa": "Park Villa Grazioli, Via Umberto Pavoni 19, 0004, Grottaferrata, Italia"
  },
  {
    "nome": "Patria Palace",
    "indirizzo": "Piazzetta Gabriele Riccardi",
    "citta": "Lecce",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "nazione": "Italia",
    "luogo": "Lecce (LE)",
    "tel": "+39 0832 245111",
    "email": "info@patriapalace.com",
    "web": "https://patriapalace.com",
    "note": "",
    "mappa": "Patria Palace, Piazzetta Gabriele Riccardi, 73100, Lecce, Italia"
  },
  {
    "nome": "Pensione Tranchina",
    "indirizzo": "Via Armando Diaz 7",
    "citta": "Scopello",
    "provincia": "TP",
    "prov": "TP",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Scopello (TP)",
    "tel": "+39 0924 541099",
    "email": "pensione.tranchina@gmail.com",
    "web": "https://www.pensionetranchina.com",
    "note": "",
    "mappa": "Pensione Tranchina, Via Armando Diaz 7, 91014, Scopello, Italia"
  },
  {
    "nome": "Pippo’s Resort",
    "indirizzo": "Via Becarino 37",
    "citta": "Poppi",
    "provincia": "AR",
    "prov": "AR",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Poppi (AR)",
    "tel": "",
    "email": "ale@pipposlittleresort.com",
    "web": "https://www.pipposlittleresort.com",
    "note": "🌳♥️",
    "mappa": "Pippo’s Resort, Via Becarino 37, 52014, Poppi, Italia"
  },
  {
    "nome": "Pirgos Mavromichali",
    "indirizzo": "",
    "citta": "Limeni Laconia",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Grecia",
    "luogo": "Limeni Laconia (GR)",
    "tel": "+30 27330 51042",
    "email": "info@pirgosmavromichali.gr",
    "web": "https://www.pirgosmavromichali.gr/en",
    "note": "Mani",
    "mappa": "Pirgos Mavromichali, 23062, Limeni Laconia, Grecia"
  },
  {
    "nome": "La Foresteria Wine Resort ",
    "indirizzo": "Contrada Passo di Gurra, Ex S.S. 115 s.p. 79, Km 91",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529986",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "La Foresteria Wine Resort , Contrada Passo di Gurra, Ex S.S. 115 s.p. 79, Km 91, 92013, Menfi, Italia"
  },
  {
    "nome": "Planeta Country House",
    "indirizzo": "Strada Provinciale 50,51 ",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529988",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "Planeta Country House, Strada Provinciale 50,51 , 92013, Menfi, Italia"
  },
  {
    "nome": "Insula Beach Club",
    "indirizzo": "Via dei Pioppi – Lido Fiori",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529987",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "Insula Beach Club, Via dei Pioppi – Lido Fiori, 92013, Menfi, Italia"
  },
  {
    "nome": "Palazzo Planeta",
    "indirizzo": "Via Principe di Belmonte 68",
    "citta": "Palermo",
    "provincia": "PA",
    "prov": "PA",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Palermo (PA)",
    "tel": "+39 091 7330940",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "Palazzo Planeta, Via Principe di Belmonte 68, 90139, Palermo, Italia"
  },
  {
    "nome": "Casa Panitteri",
    "indirizzo": "Vicolo Puccio 21",
    "citta": "Sambuca di Sicilia",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Sambuca di Sicilia (AG)",
    "tel": "+39 0925 1955460",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "Casa Panitteri, Vicolo Puccio 21, 92017, Sambuca di Sicilia, Italia"
  },
  {
    "nome": "Case Sparse",
    "indirizzo": "Contrada Buonivini",
    "citta": "Noto",
    "provincia": "SR",
    "prov": "SR",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Noto (SR)",
    "tel": "+39 0925 1955460",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’Azienda Planeta",
    "mappa": "Case Sparse, Contrada Buonivini, 96017, Noto, Italia"
  },
  {
    "nome": "Principe di Savoia",
    "indirizzo": "Piazza della Repubblica 17",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Milano (MI)",
    "tel": "+39 02 62301",
    "email": "club10.HPS@dorchestercollection.com",
    "web": "https://www.hotelprincipedisavoia.com/contattaci-hotel-p",
    "note": "",
    "mappa": "Principe di Savoia, Piazza della Repubblica 17, 20124, Milano, Italia"
  },
  {
    "nome": "Principe Forte dei Marmi",
    "indirizzo": "Viale Ammiraglio Morin 67",
    "citta": "Forte dei Marmi",
    "provincia": "LU",
    "prov": "LU",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Forte dei Marmi (LU)",
    "tel": "+39 0584 783636",
    "email": "info@principefortedeimarmi.com",
    "web": "https://principefortedeimarmi.com/it",
    "note": "",
    "mappa": "Principe Forte dei Marmi, Viale Ammiraglio Morin 67, 55042, Forte dei Marmi, Italia"
  },
  {
    "nome": "Raphaël",
    "indirizzo": "Largo Febo 2",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Roma (RM)",
    "tel": "+39 06 682831",
    "email": "rev@raphaelhotel.com",
    "web": "https://www.raphaelhotel.com",
    "note": "",
    "mappa": "Raphaël, Largo Febo 2, 00186, Roma, Italia"
  },
  {
    "nome": "Rector",
    "indirizzo": "Paseo Rector Esperabé 10",
    "citta": "Salamanca",
    "provincia": "ES",
    "prov": "ES",
    "regione": "Spagna",
    "nazione": "Spagna",
    "luogo": "Salamanca (ES)",
    "tel": "+34 923 218 482",
    "email": "info@hotelrector.com",
    "web": "https://www.hotelrector.com",
    "note": "",
    "mappa": "Rector, Paseo Rector Esperabé 10, 37008, Salamanca, Spagna"
  },
  {
    "nome": "Relais Castello di Morcote",
    "indirizzo": "Portich de Sura",
    "citta": "Vico Morcote",
    "provincia": "TI",
    "prov": "TI",
    "regione": "Svizzera",
    "nazione": "Svizzera",
    "luogo": "Vico Morcote (TI)",
    "tel": "+41 91 980 22 52",
    "email": "relais@castellodimorcote.ch",
    "web": "https://www.relaiscastellodimorcote.ch",
    "note": "Ticino ❤️🌳",
    "mappa": "Relais Castello di Morcote, Portich de Sura, 6921, Vico Morcote, Svizzera"
  },
  {
    "nome": "Relais Maso di Villa",
    "indirizzo": "Via Col di Guarda 15",
    "citta": "Susegana",
    "provincia": "TV",
    "prov": "TV",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Susegana (TV)",
    "tel": "+39 0438 841414",
    "email": "info@masodivilla.it",
    "web": "https://www.masodivilla.it/it/",
    "note": "",
    "mappa": "Relais Maso di Villa, Via Col di Guarda 15, 31058, Susegana, Italia"
  },
  {
    "nome": "Relais San Vigilio",
    "indirizzo": "Via al Castello 7",
    "citta": "Bergamo Alta",
    "provincia": "BG",
    "prov": "BG",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Bergamo Alta (BG)",
    "tel": "+39 035 2650987",
    "email": "info@relaissanvigilio.it",
    "web": "https://www.relaissanvigilio.it",
    "note": "",
    "mappa": "Relais San Vigilio, Via al Castello 7, 24129, Bergamo Alta, Italia"
  },
  {
    "nome": "Relais Villa d'Amelia",
    "indirizzo": "Località Manera 1",
    "citta": "Benevello",
    "provincia": "CN",
    "prov": "CN",
    "regione": "Piemonte",
    "nazione": "Italia",
    "luogo": "Benevello (CN)",
    "tel": "+39 0173 529225",
    "email": "info@villadamelia.com",
    "web": "https://www.villadamelia.com",
    "note": "",
    "mappa": "Relais Villa d'Amelia, Località Manera 1, 12050, Benevello, Italia"
  },
  {
    "nome": "Residenza Scaravelli",
    "indirizzo": "Portici Broletto 22",
    "citta": "Mantova",
    "provincia": "MN",
    "prov": "MN",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Mantova (MN)",
    "tel": "+39 0376 226161",
    "email": "residenza@scaravelli.it",
    "web": "https://www.scaravelli.it/residenza",
    "note": "",
    "mappa": "Residenza Scaravelli, Portici Broletto 22, 46100, Mantova, Italia"
  },
  {
    "nome": "Retici Balzi",
    "indirizzo": "Via Panoramica 2",
    "citta": "Poggiridenti",
    "provincia": "SO",
    "prov": "SO",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Poggiridenti (SO)",
    "tel": "+39 0342 382092",
    "email": "info@reticibalzi.it",
    "web": "https://www.reticibalzi.it",
    "note": "",
    "mappa": "Retici Balzi, Via Panoramica 2, 23020, Poggiridenti, Italia"
  },
  {
    "nome": "Mandarin Oriental Ritz",
    "indirizzo": "Plaza de la Lealtad 5",
    "citta": "Madrid",
    "provincia": "M",
    "prov": "M",
    "regione": "Lombardia",
    "nazione": "Spagna",
    "luogo": "Madrid (M)",
    "tel": "+34 91 7016888",
    "email": "mrmad-reservations@mohg.com",
    "web": "https://www.mandarinoriental.com/en/madrid/hotel-ritz",
    "note": "",
    "mappa": "Mandarin Oriental Ritz, Plaza de la Lealtad 5, 28014, Madrid, Spagna"
  },
  {
    "nome": "Rocco Forte Hotels",
    "indirizzo": "Via del Babuino 9",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "nazione": "Italia",
    "luogo": "Roma (RM)",
    "tel": "+39 06 328881",
    "email": "reservations.derussie@roccofortehotels.com",
    "web": "https://www.roccofortehotels.com/it/hotels-and-resorts/hotel-de-russie/",
    "note": "",
    "mappa": "Rocco Forte Hotels, Via del Babuino 9, 00187, Roma, Italia"
  },
  {
    "nome": "Romeo",
    "indirizzo": "Via Cristoforo Colombo 45",
    "citta": "Napoli",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Napoli (NA)",
    "tel": "+39 081 0175001",
    "email": "welcome.na@thrromeocollection.com",
    "web": "https://www.romeohotel.com/it/romeo-napoli/",
    "note": "",
    "mappa": "Romeo, Via Cristoforo Colombo 45, 80133, Napoli, Italia"
  },
  {
    "nome": "Rovereto",
    "indirizzo": "Corso Rosmini 82/D",
    "citta": "Rovereto",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "nazione": "Italia",
    "luogo": "Rovereto (TN)",
    "tel": "+39 0464 435222",
    "email": "",
    "web": "https://www.hotelrovereto.it",
    "note": "",
    "mappa": "Rovereto, Corso Rosmini 82/D, 38068, Rovereto, Italia"
  },
  {
    "nome": "Sacher",
    "indirizzo": "Philharmonikerstraße 4",
    "citta": "Wien",
    "provincia": "W",
    "prov": "W",
    "regione": "Austria",
    "nazione": "Austria",
    "luogo": "Wien (W)",
    "tel": "+43 1 514 560",
    "email": "wien@sacher.com",
    "web": "https://www.sacher.com",
    "note": "",
    "mappa": "Sacher, Philharmonikerstraße 4, A-1010, Wien, Austria"
  },
  {
    "nome": "Salsomaggiore",
    "indirizzo": "Largo Roma 3",
    "citta": "Salsomaggiore Terme",
    "provincia": "PR",
    "prov": "PR",
    "regione": "Emilia-Romagna",
    "nazione": "Italia",
    "luogo": "Salsomaggiore Terme (PR)",
    "tel": "+39 0524 582311",
    "email": "",
    "web": "",
    "note": "",
    "mappa": "Salsomaggiore, Largo Roma 3, 43039, Salsomaggiore Terme, Italia"
  },
  {
    "nome": "San Pietro",
    "indirizzo": "Via Laurito 2",
    "citta": "Positano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Positano (SA)",
    "tel": "+39 089 812080",
    "email": "reservations@ilsanpietro.it",
    "web": "https://www.ilsanpietro.com/it/",
    "note": "",
    "mappa": "San Pietro, Via Laurito 2, 84017, Positano, Italia"
  },
  {
    "nome": "San Rocco",
    "indirizzo": "Via Gippini 11",
    "citta": "Orta San Giulio",
    "provincia": "NO",
    "prov": "NO",
    "regione": "Piemonte",
    "nazione": "Italia",
    "luogo": "Orta San Giulio (NO)",
    "tel": "+39 0322 911977",
    "email": "info@hotelsanrocco.it",
    "web": "https://www.hotelsanrocco.it",
    "note": "⛱️",
    "mappa": "San Rocco, Via Gippini 11, 28016, Orta San Giulio, Italia"
  },
  {
    "nome": "St. Regis Venezia",
    "indirizzo": "San Marco 2159",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Venezia (VE)",
    "tel": "+39 041 2400001",
    "email": "",
    "web": "https://giosrestaurantvenice.com",
    "note": "",
    "mappa": "St. Regis Venezia, San Marco 2159, 30124, Venezia, Italia"
  },
  {
    "nome": "Stella Maris",
    "indirizzo": "Punta Chiappa",
    "citta": "Camogli",
    "provincia": "GE",
    "prov": "GE",
    "regione": "Liguria",
    "nazione": "Italia",
    "luogo": "Camogli (GE)",
    "tel": "+39 0185 770285",
    "email": "info@stellamaris.cc",
    "web": "https://www.stellamaris.cc",
    "note": "Camere vista mare, taxi boat da Recco a Punta Chiappa 🌳🌅♥️",
    "mappa": "Stella Maris, Punta Chiappa, 16032, Camogli, Italia"
  },
  {
    "nome": "Tainaron Blue Retreat",
    "indirizzo": "Mani, Peliponnese",
    "citta": "Vathia",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "nazione": "Grecia",
    "luogo": "Vathia (GR)",
    "tel": "+30 2108080049 ",
    "email": "hide@tainaronblue.com",
    "web": "https://www.tainaronblue.com",
    "note": "Mani",
    "mappa": "Tainaron Blue Retreat, Mani, Peliponnese, 23062, Vathia, Grecia"
  },
  {
    "nome": "The Lowell",
    "indirizzo": "28 East 63rd Street",
    "citta": "New York",
    "provincia": "NY",
    "prov": "NY",
    "regione": "Stati Uniti",
    "nazione": "Stati Uniti d",
    "luogo": "New York (NY)",
    "tel": "+1 (212) 605-6812",
    "email": "abuchanan@lowellhotel.com",
    "web": "https://LowellHotel.com",
    "note": "",
    "mappa": "The Lowell, 28 East 63rd Street, 10065, New York, Stati Uniti d"
  },
  {
    "nome": "The Sherry Netherland",
    "indirizzo": "781 Fifth Avenue",
    "citta": "New York",
    "provincia": "NY",
    "prov": "NY",
    "regione": "Stati Uniti",
    "nazione": "Stati Un",
    "luogo": "New York (NY)",
    "tel": "+1 (212) 355-2800",
    "email": "jacosta@sherrynetherland.com",
    "web": "https://www.sherrynetherland.com",
    "note": "",
    "mappa": "The Sherry Netherland, 781 Fifth Avenue, 10022, New York, Stati Un"
  },
  {
    "nome": "Tivoli Palazzo Gaddi",
    "indirizzo": "Via del Giglio 9",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Firenze (FI)",
    "tel": "+39 331 2947089",
    "email": "info@terraerestaurant.it",
    "web": "https://www.terraerestaurant.it",
    "note": "",
    "mappa": "Tivoli Palazzo Gaddi, Via del Giglio 9, 50123, Firenze, Italia"
  },
  {
    "nome": "Tonnara di Scopello",
    "indirizzo": "Largo Tonnara",
    "citta": "Scopello",
    "provincia": "TP",
    "prov": "TP",
    "regione": "Sicilia",
    "nazione": "Italia",
    "luogo": "Scopello (TP)",
    "tel": "+39 0924 1866101",
    "email": "booking@tonnaradiscopello.it",
    "web": "https://www.tonnaradiscopello.it",
    "note": "Hotel sul mare",
    "mappa": "Tonnara di Scopello, Largo Tonnara, 91014, Scopello, Italia"
  },
  {
    "nome": "Villa Abbazia",
    "indirizzo": "Via Martiri della Libertà 8",
    "citta": "Follina",
    "provincia": "TV",
    "prov": "TV",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Follina (TV)",
    "tel": "+39 0438 971277",
    "email": "info@hotelabbazia.it",
    "web": "https://www.hotelabbazia.com/it/",
    "note": "",
    "mappa": "Villa Abbazia, Via Martiri della Libertà 8, 31051, Follina, Italia"
  },
  {
    "nome": "Villa Castagnola",
    "indirizzo": "Via Pico 9",
    "citta": "Lugano",
    "provincia": "TI",
    "prov": "TI",
    "regione": "Svizzera",
    "nazione": "Svizzera",
    "luogo": "Lugano (TI)",
    "tel": "+41 91 9732555",
    "email": "info@villacastagnola.com",
    "web": "https://www.villacastagnola.com",
    "note": "Vista lago 🌳❤️",
    "mappa": "Villa Castagnola, Via Pico 9, 6900, Lugano, Svizzera"
  },
  {
    "nome": "Villa Cicchi",
    "indirizzo": "Via Salaria Superiore 137",
    "citta": "Abbazia di Rosara",
    "provincia": "AP",
    "prov": "AP",
    "regione": "Marche",
    "nazione": "Italia",
    "luogo": "Abbazia di Rosara (AP)",
    "tel": "",
    "email": "mariaelenacicchi@gmail.com",
    "web": "https://www.villacicchi.it",
    "note": "Residenza di campagna 🌳❤️",
    "mappa": "Villa Cicchi, Via Salaria Superiore 137, 63100, Abbazia di Rosara, Italia"
  },
  {
    "nome": "Villa Cora",
    "indirizzo": "Viale Machiavelli 18",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "nazione": "Italia",
    "luogo": "Firenze (FI)",
    "tel": "+39 055 228790",
    "email": "info@villacora.it",
    "web": "https://www.villacora.it",
    "note": "Sontuosa residenza, vista sulla città 🌳❤️",
    "mappa": "Villa Cora, Viale Machiavelli 18, 50125, Firenze, Italia"
  },
  {
    "nome": "Villa Cortine Palace",
    "indirizzo": "Viale C. Gennari 2",
    "citta": "Sirmione",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Sirmione (BS)",
    "tel": "+39 030 9905890",
    "email": "roberto.cappelletto@hotelvillacorti",
    "web": "https://www.hotelvillacortine.com",
    "note": "Sontuosa residenza in un parco 🌳❤️",
    "mappa": "Villa Cortine Palace, Viale C. Gennari 2, 25019, Sirmione, Italia"
  },
  {
    "nome": "Villa d’Este",
    "indirizzo": "Via Regina 40",
    "citta": "Cernobbio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "nazione": "Italia",
    "luogo": "Cernobbio (CO)",
    "tel": "+39 031 3481",
    "email": "info@villadeste.it",
    "web": "https://www://www.villadeste.com/it/",
    "note": "",
    "mappa": "Villa d’Este, Via Regina 40, 22012, Cernobbio, Italia"
  },
  {
    "nome": "Villa Franceschi",
    "indirizzo": "Via Don Giovanni Minzoni 27",
    "citta": "Mira",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "nazione": "Italia",
    "luogo": "Mira (VE)",
    "tel": "+39 0414266531",
    "email": "info@villafranceschi.com",
    "web": "https://wwwvillafranceschi.com",
    "note": "",
    "mappa": "Villa Franceschi, Via Don Giovanni Minzoni 27, 30034, Mira, Italia"
  },
  {
    "nome": "Villa Gallici",
    "indirizzo": "Avenue de la Violette",
    "citta": "Aix en Provence",
    "provincia": "",
    "prov": "",
    "regione": "France",
    "nazione": "France",
    "luogo": "Aix en Provence",
    "tel": "+33 (0) 4 42 32 92 3",
    "email": "gallici@relaischateaux.fr",
    "web": "https://www.villagallici.com",
    "note": "",
    "mappa": "Villa Gallici, Avenue de la Violette, 13100, Aix en Provence, France"
  },
  {
    "nome": "Villa Maria",
    "indirizzo": "Contrada Pretaro",
    "citta": "Francavilla al Mare",
    "provincia": "CH",
    "prov": "CH",
    "regione": "Abruzzo",
    "nazione": "Italia",
    "luogo": "Francavilla al Mare (CH)",
    "tel": "+39 085 450051",
    "email": "info@hvillamaria.it",
    "web": "https://hvillamaria.it",
    "note": "Vista mare 🌳❤️",
    "mappa": "Villa Maria, Contrada Pretaro, 66023, Francavilla al Mare, Italia"
  },
  {
    "nome": "Villa Treville",
    "indirizzo": "Via Arienzo 30",
    "citta": "Positano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "nazione": "Italia",
    "luogo": "Positano (SA)",
    "tel": "+39 089 8122401",
    "email": "direttore@villatreville.it",
    "web": "https://www.villatreville.it",
    "note": "Vista mare 🌳❤️",
    "mappa": "Villa Treville, Via Arienzo 30, 84017, Positano, Italia"
  },
  {
    "nome": "Villa Santa Barbara",
    "indirizzo": "Via Federico Giunchi",
    "citta": "San Luca",
    "provincia": "PG",
    "prov": "PG",
    "regione": "Umbria",
    "nazione": "Italia",
    "luogo": "San Luca (PG)",
    "tel": "+39 0742 399402",
    "email": "info@hotelvillasantabarbara.com",
    "web": "https://www.hotelvillasantabarbara.com",
    "note": "Residenza di campagna tra i vigneti ⛰️ 🌳❤️",
    "mappa": "Villa Santa Barbara, Via Federico Giunchi, 06036, San Luca, Italia"
  }
];
var HOTEL_PROVCITTA={
  "Calabria": [
    "CS"
  ],
  "Russia": [
    ""
  ],
  "Puglia": [
    "BR",
    "LE"
  ],
  "Valle d Aosta": [
    "AO"
  ],
  "Toscana": [
    "AR",
    "FI",
    "GR",
    "LU",
    "SI"
  ],
  "Lombardia": [
    "BG",
    "BS",
    "CO",
    "LC",
    "M",
    "MI",
    "MN",
    "Mi",
    "SO"
  ],
  "Campania": [
    "NA",
    "SA"
  ],
  "China": [
    ""
  ],
  "Lazio": [
    "FR",
    "RM",
    "VT"
  ],
  "Piemonte": [
    "AL",
    "CN",
    "NO",
    "TO"
  ],
  "Trentino-Alto Adige": [
    "BZ",
    "TN"
  ],
  "Veneto": [
    "TV",
    "VE"
  ],
  "Liguria": [
    "GE",
    "IM",
    "SP",
    "SV"
  ],
  "United Kingdom": [
    ""
  ],
  "France": [
    ""
  ],
  "Friuli-Venezia Giulia": [
    "TS"
  ],
  "Thailand": [
    ""
  ],
  "Italia": [
    ""
  ],
  "Abruzzo": [
    "AQ",
    "CH"
  ],
  "Emilia-Romagna": [
    "PR",
    "RN"
  ],
  "Grecia": [
    ""
  ],
  "Sardegna": [
    "SS",
    "VS"
  ],
  "Marche": [
    "AN",
    "AP"
  ],
  "Perù": [
    ""
  ],
  "Regno Unito": [
    "GB"
  ],
  "Sicilia": [
    "AG",
    "PA",
    "SR",
    "TP"
  ],
  "Spagna": [
    "ES"
  ],
  "Svizzera": [
    "TI"
  ],
  "Austria": [
    "W"
  ],
  "Stati Uniti": [
    "NY"
  ],
  "Umbria": [
    "PG"
  ]
};
