/* T42 VIAGGIOPERDUE GUIDA ALBERGHI */
var HOTEL=[
  {
    "nome": "Aquila Edelweiss",
    "indirizzo": "Via Stazione 15",
    "citta": "Camigliatello Silano",
    "provincia": "CS",
    "prov": "CS",
    "regione": "Calabria",
    "luogo": "Camigliatello Silano (CS)",
    "tel": "+39 0984 578044",
    "telefono": "+39 0984 578044",
    "cellulare": "",
    "email": "info@hotelaquilaedelweiss.com",
    "web": "https://www.hotelaquilaedelweiss.com",
    "note": "⛰️",
    "mappa": "Via Stazione 15, Camigliatello Silano, CS"
  },
  {
    "nome": "Astoria",
    "indirizzo": "Bolshaya Morskaya str. 39",
    "citta": "St. Petersburg",
    "provincia": "RU",
    "prov": "RU",
    "regione": "Russia",
    "luogo": "St. Petersburg (RU)",
    "tel": "+7 (812) 494-57-92",
    "telefono": "+7 (812) 494-57-92",
    "cellulare": "+7 (921) 951-53-18",
    "email": "",
    "web": "https://www.roccofortehotels.ru/en",
    "note": "👑",
    "mappa": "Bolshaya Morskaya str. 39, St. Petersburg, RU"
  },
  {
    "nome": "BelAmi",
    "indirizzo": "Via Roma 86",
    "citta": "Maglie",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "luogo": "Maglie (LE)",
    "tel": "+39 0836 312930",
    "telefono": "+39 0836 312930",
    "cellulare": "+39 348 7983070",
    "email": "info@bel-ami.it",
    "web": "https://www.hotelbelami.it",
    "note": "",
    "mappa": "Via Roma 86, Maglie, LE"
  },
  {
    "nome": "Bellevue",
    "indirizzo": "Rue Grand Paradis 22",
    "citta": "Cogne",
    "provincia": "AO",
    "prov": "AO",
    "regione": "Valle d'Aosta",
    "luogo": "Cogne (AO)",
    "tel": "+39 0165 74825",
    "telefono": "+39 0165 74825",
    "cellulare": "",
    "email": "info@hotelbellevue.it",
    "web": "https://www.hotelbellevue.it/it/",
    "note": "⛰️ 🌳 ♥️",
    "mappa": "Rue Grand Paradis 22, Cogne, AO"
  },
  {
    "nome": "Berghotel Randolins",
    "indirizzo": "Via Curtins 2",
    "citta": "Sankt Moritz",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Svizzera",
    "luogo": "Sankt Moritz (GR)",
    "tel": "+41 (0) 81 8308383",
    "telefono": "+41 (0) 81 8308383",
    "cellulare": "",
    "email": "willkommen@randolins.ch",
    "web": "https://www.randolins.ch/it/",
    "note": "⛰️ 🌳",
    "mappa": "Via Curtins 2, Sankt Moritz, GR"
  },
  {
    "nome": "Bianca Relais",
    "indirizzo": "Via Dante Alighieri 18",
    "citta": "Oggiono",
    "provincia": "LC",
    "prov": "LC",
    "regione": "Lombardia",
    "luogo": "Oggiono (LC)",
    "tel": "+39 0341 1831110",
    "telefono": "+39 0341 1831110",
    "cellulare": "",
    "email": "reservation@biancarelais.it",
    "web": "https://biancarelais.it",
    "note": "🌳 🌅 ♥️",
    "mappa": "Via Dante Alighieri 18, Oggiono, LC"
  },
  {
    "nome": "Bis Osteria Contemporanea",
    "indirizzo": "Via XX Settembre 50",
    "citta": "Colle di Val d'Elsa",
    "provincia": "SI",
    "prov": "SI",
    "regione": "Toscana",
    "luogo": "Colle di Val d'Elsa (SI)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 338 7706128",
    "email": "info@osteriabis.it",
    "web": "https://www.osteriabis.it/",
    "note": "Vista sulla campagna toscana 🌳♥️",
    "mappa": "Via XX Settembre 50, Colle di Val d'Elsa, SI"
  },
  {
    "nome": "Borgo Santandrea",
    "indirizzo": "Via Giovanni Augustariccio 33",
    "citta": "Amalfi",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Amalfi (SA)",
    "tel": "+39 089 831148",
    "telefono": "+39 089 831148",
    "cellulare": "",
    "email": "info@borgosantandrea.it",
    "web": "https://borgosantandrea.it",
    "note": "🌳 🌅 ♥️",
    "mappa": "Via Giovanni Augustariccio 33, Amalfi, SA"
  },
  {
    "nome": "Borgo Santo Pietro",
    "indirizzo": "Località Palazzetto",
    "citta": "Chiusdino",
    "provincia": "SI",
    "prov": "SI",
    "regione": "Toscana",
    "luogo": "Chiusdino (SI)",
    "tel": "+30 0577751222",
    "telefono": "+30 0577751222",
    "cellulare": "+39 366 5875516",
    "email": "laura@borgosantopietro.com",
    "web": "https://www.borgosantopietro.com",
    "note": "🌳 ♥️",
    "mappa": "Località Palazzetto, Chiusdino, SI"
  },
  {
    "nome": "Bulgari Milano",
    "indirizzo": "Via Privata Fratelli Gabba 7b",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "luogo": "Milano (MI)",
    "tel": "+39028058051",
    "telefono": "+39028058051",
    "cellulare": "+393420859801",
    "email": "milano@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/milan/",
    "note": "Albergo in stile contemporaneo immerso in un parco 🌳♥️",
    "mappa": "Via Privata Fratelli Gabba 7b, Milano, MI"
  },
  {
    "nome": "Bulgari Pechino",
    "indirizzo": "No.8 Xinyuan South Road\\, Chaoyang District",
    "citta": "Beijing",
    "provincia": "CN",
    "prov": "CN",
    "regione": "Cina",
    "luogo": "Beijing (CN)",
    "tel": "+86 10 8555 8555",
    "telefono": "+86 10 8555 8555",
    "cellulare": "",
    "email": "beijing@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/beijing",
    "note": "👑",
    "mappa": "No.8 Xinyuan South Road\\, Chaoyang District, Beijing, CN"
  },
  {
    "nome": "Bulgari Roma",
    "indirizzo": "Piazza Augusto Imperatore 10",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "luogo": "Roma (RM)",
    "tel": "+39 06 36080 400",
    "telefono": "+39 06 36080 400",
    "cellulare": "",
    "email": "roma@bulgarihotels.com",
    "web": "https://www.bulgarihotels.com/it_IT/rome",
    "note": "Albergo in stile contemporaneo 👑 ♥️",
    "mappa": "Piazza Augusto Imperatore 10, Roma, RM"
  },
  {
    "nome": "Capricorno",
    "indirizzo": "Via Case Sparse 21",
    "citta": "Sauze D'Oulx",
    "provincia": "TO",
    "prov": "TO",
    "regione": "Piemonte",
    "luogo": "Sauze D'Oulx (TO)",
    "tel": "+39 0122 850273",
    "telefono": "+39 0122 850273",
    "cellulare": "",
    "email": "info@chaletilcapricorno.it",
    "web": "https://chaletilcapricorno.it",
    "note": "⛰♥️️",
    "mappa": "Via Case Sparse 21, Sauze D'Oulx, TO"
  },
  {
    "nome": "Carlton",
    "indirizzo": "Via Senato 7",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "luogo": "Milano (MI)",
    "tel": "+39 02 811221",
    "telefono": "+39 02 811221",
    "cellulare": "",
    "email": "reservations.carlton@roccofortehotels.com",
    "web": "https://www.roccofortehotels.com/it/hotels-and-resorts/the-carlton-milan/",
    "note": "♥️",
    "mappa": "Via Senato 7, Milano, MI"
  },
  {
    "nome": "Caruso",
    "indirizzo": "Piazza San Giovanni Del Toro 2",
    "citta": "Ravello",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Ravello (SA)",
    "tel": "+39 089 858801",
    "telefono": "+39 089 858801",
    "cellulare": "",
    "email": "",
    "web": "https://www.belmond.com/it/hotels/europe/italy/amalfi-c",
    "note": "Splendida vista sulla Costiera Amalfitana 👑 🌳 🌅 🏖️ ♥️",
    "mappa": "Piazza San Giovanni Del Toro 2, Ravello, SA"
  },
  {
    "nome": "Casa Fantini",
    "indirizzo": "Piazza Motta angolo Via Roma 2",
    "citta": "Pella",
    "provincia": "NO",
    "prov": "NO",
    "regione": "Piemonte",
    "luogo": "Pella (NO)",
    "tel": "+39 0322 969893",
    "telefono": "+39 0322 969893",
    "cellulare": "",
    "email": "info@casafantinilaketime.com",
    "web": "https://www.casafantinilaketime.com/it",
    "note": "🌅 🌳♥️",
    "mappa": "Piazza Motta angolo Via Roma 2, Pella, NO"
  },
  {
    "nome": "Casa Panitteri",
    "indirizzo": "Vicolo Puccio 21",
    "citta": "Sambuca di Sicilia",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "luogo": "Sambuca di Sicilia (AG)",
    "tel": "+39 0925 1955460",
    "telefono": "+39 0925 1955460",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Vicolo Puccio 21, Sambuca di Sicilia, AG"
  },
  {
    "nome": "Case Sparse",
    "indirizzo": "Contrada Buonivini",
    "citta": "Noto",
    "provincia": "SR",
    "prov": "SR",
    "regione": "Sicilia",
    "luogo": "Noto (SR)",
    "tel": "+39 0925 1955460",
    "telefono": "+39 0925 1955460",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Contrada Buonivini, Noto, SR"
  },
  {
    "nome": "Chalet del Sogno",
    "indirizzo": "Via Spinale 37b",
    "citta": "Madonna di Campiglio",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "luogo": "Madonna di Campiglio (TN)",
    "tel": "+39 0465 441033",
    "telefono": "+39 0465 441033",
    "cellulare": "+39 348 4481148",
    "email": "direzione@hotelchaletdelsogno.com",
    "web": "https://www.hotelchaletdelsognocampiglio.com",
    "note": "⛰️ 🌳♥️",
    "mappa": "Via Spinale 37b, Madonna di Campiglio, TN"
  },
  {
    "nome": "Ciasa Salares",
    "indirizzo": "Strada Pre de Vì 31",
    "citta": "San Cassiano in Badia",
    "provincia": "BZ",
    "prov": "BZ",
    "regione": "Trentino-Alto Adige",
    "luogo": "San Cassiano in Badia (BZ)",
    "tel": "+39 0471 849445",
    "telefono": "+39 0471 849445",
    "cellulare": "",
    "email": "info@ciasasalares.it",
    "web": "https://www.ciasasalares.it",
    "note": "⛰️ 🌳♥️",
    "mappa": "Strada Pre de Vì 31, San Cassiano in Badia, BZ"
  },
  {
    "nome": "Cipriani",
    "indirizzo": "Giudecca 10",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "luogo": "Venezia (VE)",
    "tel": "+39 0185 2353451",
    "telefono": "+39 0185 2353451",
    "cellulare": "",
    "email": "",
    "web": "https://www.belmond.com/it/hotels/europe/italy/venice/belmond-hotel-cipriani/",
    "note": "👑 🌳 🌅 🏖️ ♥️",
    "mappa": "Giudecca 10, Venezia, VE"
  },
  {
    "nome": "Claudio Le Terrazze",
    "indirizzo": "Via XXV Aprile 37",
    "citta": "Bergeggi",
    "provincia": "SV",
    "prov": "SV",
    "regione": "Liguria",
    "luogo": "Bergeggi (SV)",
    "tel": "+39 019 859750",
    "telefono": "+39 019 859750",
    "cellulare": "",
    "email": "info@hotelclaudio.it",
    "web": "https://www.hotelclaudio.it",
    "note": "🌳 🌅 🏖️ ♥️",
    "mappa": "Via XXV Aprile 37, Bergeggi, SV"
  },
  {
    "nome": "Connaught Hotel",
    "indirizzo": "Carlos Place Mayfair",
    "citta": "London",
    "provincia": "GB",
    "prov": "GB",
    "regione": "Inghilterra",
    "luogo": "London (GB)",
    "tel": "",
    "telefono": "",
    "cellulare": "",
    "email": "",
    "web": "https://www.maybourne.com/en/hotels/the-connaught",
    "note": "👑 ♥️",
    "mappa": "Carlos Place Mayfair, London, GB"
  },
  {
    "nome": "Da Alvise",
    "indirizzo": "Via 1° Maggio 5",
    "citta": "Sutrio",
    "provincia": "UD",
    "prov": "UD",
    "regione": "Friuli-Venezia Giulia",
    "luogo": "Sutrio (UD)",
    "tel": "+39 0433 778692",
    "telefono": "+39 0433 778692",
    "cellulare": "",
    "email": "prenotazioni@osteriaalvise.it",
    "web": "https://www.osteriaalvise.it",
    "note": "♥️",
    "mappa": "Via 1° Maggio 5, Sutrio, UD"
  },
  {
    "nome": "Du Clos",
    "indirizzo": "55 Chemin des Écoles",
    "citta": "Le Rouret",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Le Rouret (F)",
    "tel": "+33 (0) 4 93 40 78 85",
    "telefono": "+33 (0) 4 93 40 78 85",
    "cellulare": "",
    "email": "contact@hotel-du-clos.com",
    "web": "https://hotel-du-clos.com",
    "note": "",
    "mappa": "55 Chemin des Écoles, Le Rouret, F"
  },
  {
    "nome": "Eco del Mare",
    "indirizzo": "Località Maramozza 4",
    "citta": "Lerici",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "luogo": "Lerici (SP)",
    "tel": "+39 0187 964239",
    "telefono": "+39 0187 964239",
    "cellulare": "+39 327 7787052",
    "email": "info@ecodelmare.it",
    "web": "https://ecodelmare.it",
    "note": "🌳 🌅 ♥️",
    "mappa": "Località Maramozza 4, Lerici, SP"
  },
  {
    "nome": "Eden",
    "indirizzo": "Località Sistiana 42",
    "citta": "Duino Aurisina",
    "provincia": "TS",
    "prov": "TS",
    "regione": "Friuli-Venezia Giulia",
    "luogo": "Duino Aurisina (TS)",
    "tel": "+39 040 2907042",
    "telefono": "+39 040 2907042",
    "cellulare": "345 3361760",
    "email": "info@edensistiana.it",
    "web": "https://www.edensistiana.it",
    "note": "",
    "mappa": "Località Sistiana 42, Duino Aurisina, TS"
  },
  {
    "nome": "Eden",
    "indirizzo": "Via Ludovisi 49",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "luogo": "Roma (RM)",
    "tel": "+39 06 478121",
    "telefono": "+39 06 478121",
    "cellulare": "",
    "email": "",
    "web": "https://www.dorchestercollection.com/it/rome/hotel-eden",
    "note": "🌄 ♥️",
    "mappa": "Via Ludovisi 49, Roma, RM"
  },
  {
    "nome": "Eveline Portosole",
    "indirizzo": "Corso Cavallotti 111",
    "citta": "San Remo",
    "provincia": "IM",
    "prov": "IM",
    "regione": "Liguria",
    "luogo": "San Remo (IM)",
    "tel": "+39 0184 503430",
    "telefono": "+39 0184 503430",
    "cellulare": "",
    "email": "mailto:hotel@evelineportosole.com",
    "web": "https://www.evelineportosole.com",
    "note": "",
    "mappa": "Corso Cavallotti 111, San Remo, IM"
  },
  {
    "nome": "Four Seasons Bangkok",
    "indirizzo": "300 Charoen Krung Road, Sathorn",
    "citta": "Bangkok",
    "provincia": "TH",
    "prov": "TH",
    "regione": "Tailandia",
    "luogo": "Bangkok (TH)",
    "tel": "+66 (0) 2 032 0887",
    "telefono": "+66 (0) 2 032 0887",
    "cellulare": "",
    "email": "reservations.bangkok@fourseasons.com",
    "web": "https://www.fourseasons.com/bangkok",
    "note": "👑 ♥️",
    "mappa": "300 Charoen Krung Road, Sathorn, Bangkok, TH"
  },
  {
    "nome": "Four Seasons Geneva",
    "indirizzo": "33 Quai des Bergues",
    "citta": "Geneva",
    "provincia": "GE",
    "prov": "GE",
    "regione": "Svizzera",
    "luogo": "Geneva (GE)",
    "tel": "",
    "telefono": "",
    "cellulare": "+41 (22) 908 70 53",
    "email": "",
    "web": "https://www.fourseasons.com/geneva",
    "note": "🌅 ♥️",
    "mappa": "33 Quai des Bergues, Geneva, GE"
  },
  {
    "nome": "Four Seasons Milano",
    "indirizzo": "Via Gesù 6/8",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "luogo": "Milano (MI)",
    "tel": "+39 02 77088",
    "telefono": "+39 02 77088",
    "cellulare": "",
    "email": "",
    "web": "https://www.fourseasons.com/milan",
    "note": "👑 🌳 ♥️",
    "mappa": "Via Gesù 6/8, Milano, MI"
  },
  {
    "nome": "Grand Hotel della Posta",
    "indirizzo": "Piazza Garibaldi 19",
    "citta": "Sondrio",
    "provincia": "SO",
    "prov": "SO",
    "regione": "Lombardia",
    "luogo": "Sondrio (SO)",
    "tel": "+39 0342 200397",
    "telefono": "+39 0342 200397",
    "cellulare": "",
    "email": "info@grandhoteldellaposta.eu",
    "web": "https://www.grandhoteldellaposta.eu",
    "note": "",
    "mappa": "Piazza Garibaldi 19, Sondrio, SO"
  },
  {
    "nome": "Grand Hotel Tremezzo",
    "indirizzo": "Via Regina 8",
    "citta": "Tremezzina",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "luogo": "Tremezzina (CO)",
    "tel": "+39 0344 42491",
    "telefono": "+39 0344 42491",
    "cellulare": "",
    "email": "",
    "web": "https://www.grandhoteltremezzo.com",
    "note": "👑 🌳 🌅 🏖️ ♥️",
    "mappa": "Via Regina 8, Tremezzina, CO"
  },
  {
    "nome": "Grand Hotel Villa Serbelloni",
    "indirizzo": "Via Roma 1",
    "citta": "Bellagio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "luogo": "Bellagio (CO)",
    "tel": "+39 031 950216",
    "telefono": "+39 031 950216",
    "cellulare": "",
    "email": "info@villaserbelloni.com",
    "web": "https://www.villaserbelloni.com",
    "note": "👑 🌳 🌅 🏖️ ♥️",
    "mappa": "Via Roma 1, Bellagio, CO"
  },
  {
    "nome": "Gritti Palace",
    "indirizzo": "Campo Santa Maria del Giglio 2467",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "luogo": "Venezia (VE)",
    "tel": "+39 041 794611",
    "telefono": "+39 041 794611",
    "cellulare": "",
    "email": "",
    "web": "https://www.marriott.com/en-us/hotels/vcegl-the-gritti-palace-a-luxury-collection-hotel-venice/overview/",
    "note": "👑 🌅♥️",
    "mappa": "Campo Santa Maria del Giglio 2467, Venezia, VE"
  },
  {
    "nome": "Heart of Trento",
    "indirizzo": "Vicolo del Vò 27 Interno 24-23",
    "citta": "Trento",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "luogo": "Trento (TN)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 340 317 3939",
    "email": "trento.loftrooms@gmail.com",
    "web": "https://trentoloftroom.it",
    "note": "",
    "mappa": "Vicolo del Vò 27 Interno 24-23, Trento, TN"
  },
  {
    "nome": "Helvetia & Bristol",
    "indirizzo": "Via dei Pescioni 2",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "luogo": "Firenze (FI)",
    "tel": "+3905526651",
    "telefono": "+3905526651",
    "cellulare": "",
    "email": "",
    "web": "https://collezione.starhotels.com/it/i-nostri-hotel/hel",
    "note": "♥️",
    "mappa": "Via dei Pescioni 2, Firenze, FI"
  },
  {
    "nome": "Hotel Casa Angelina",
    "indirizzo": "Via Capriglione 147",
    "citta": "Praiano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Praiano (SA)",
    "tel": "+39 089 8131333",
    "telefono": "+39 089 8131333",
    "cellulare": "+39 335 5343561",
    "email": "reservation@casangelina.com",
    "web": "https://www.casangelina.com",
    "note": "🌳 🌅 🏖♥️️",
    "mappa": "Via Capriglione 147, Praiano, SA"
  },
  {
    "nome": "Hotellerie de Mascognaz",
    "indirizzo": "Via Dondeynaz 12",
    "citta": "Ayas",
    "provincia": "AO",
    "prov": "AO",
    "regione": "Valle d'Aosta",
    "luogo": "Ayas (AO)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 338 7295708",
    "email": "info@hotelleriedemascognaz.com",
    "web": "https://www.hotelleriedemascognaz.com",
    "note": "🌄 ⛰️ 🌳♥️",
    "mappa": "Via Dondeynaz 12, Ayas, AO"
  },
  {
    "nome": "Il Borro",
    "indirizzo": "Località Il Borro 1",
    "citta": "San Giustino Valdarno",
    "provincia": "AR",
    "prov": "AR",
    "regione": "Toscana",
    "luogo": "San Giustino Valdarno (AR)",
    "tel": "+39 055 977053",
    "telefono": "+39 055 977053",
    "cellulare": "",
    "email": "ilborro@ilborro.it",
    "web": "https://www.ilborro.it",
    "note": "🌳🌄♥️",
    "mappa": "Località Il Borro 1, San Giustino Valdarno, AR"
  },
  {
    "nome": "Il Gatto Bianco",
    "indirizzo": "Viale Appennini 3",
    "citta": "Pescocostanzo",
    "provincia": "AQ",
    "prov": "AQ",
    "regione": "Abruzzo",
    "luogo": "Pescocostanzo (AQ)",
    "tel": "+39 0864 641651",
    "telefono": "+39 0864 641651",
    "cellulare": "",
    "email": "info@ilgattobianco.it",
    "web": "https://www.ilgattobianco.com",
    "note": "⛰♥️️",
    "mappa": "Viale Appennini 3, Pescocostanzo, AQ"
  },
  {
    "nome": "Il Pellicano",
    "indirizzo": "Località Sbarcatello",
    "citta": "Porto Ercole",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "luogo": "Porto Ercole (GR)",
    "tel": "+39 0564 858111",
    "telefono": "+39 0564 858111",
    "cellulare": "",
    "email": "reservations@pellicanohotels.com",
    "web": "https://www.pellicanohotels.com/it/hotels/hotel-il-pellicano/",
    "note": "🌳🌅 🏖♥️️",
    "mappa": "Località Sbarcatello, Porto Ercole, GR"
  },
  {
    "nome": "Il Villino",
    "indirizzo": "Via Costantino Ruggeri 48",
    "citta": "Sant’Arcangelo di Romagna",
    "provincia": "RN",
    "prov": "RN",
    "regione": "Emilia-Romagna",
    "luogo": "Sant’Arcangelo di Romagna (RN)",
    "tel": "+39 0541 685959",
    "telefono": "+39 0541 685959",
    "cellulare": "",
    "email": "info@hotelilvillino.it",
    "web": "https://www.hotelilvillino.it",
    "note": "🌳♥️",
    "mappa": "Via Costantino Ruggeri 48, Sant’Arcangelo di Romagna, RN"
  },
  {
    "nome": "Insula Beach Club",
    "indirizzo": "Via dei Pioppi – Lido Fiori",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529987",
    "telefono": "+39 0925 529987",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Via dei Pioppi – Lido Fiori, Menfi, AG"
  },
  {
    "nome": "Kronenhof",
    "indirizzo": "Via Maistra",
    "citta": "Pontresina",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Svizzera",
    "luogo": "Pontresina (GR)",
    "tel": "+41 (0) 81 830 32 23",
    "telefono": "+41 (0) 81 830 32 23",
    "cellulare": "",
    "email": "info@kronenhof.com",
    "web": "https://www.kronenhof.com",
    "note": "👑 ⛰️🌳♥️",
    "mappa": "Via Maistra, Pontresina, GR"
  },
  {
    "nome": "Kuerbishof",
    "indirizzo": "Via Guggal 23",
    "citta": "Anterivo",
    "provincia": "BZ",
    "prov": "BZ",
    "regione": "Trentino-Alto Adige",
    "luogo": "Anterivo (BZ)",
    "tel": "+39 0471 882140",
    "telefono": "+39 0471 882140",
    "cellulare": "",
    "email": "info@kuerbishof.it",
    "web": "https://www.kuerbishof.it",
    "note": "⛰️ 🌳 ♥️",
    "mappa": "Via Guggal 23, Anterivo, BZ"
  },
  {
    "nome": "Kyrimai",
    "indirizzo": "Mani, Peliponnese",
    "citta": "Gerolimenas",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Grecia",
    "luogo": "Gerolimenas (GR)",
    "tel": "(+30) 27330 54288",
    "telefono": "(+30) 27330 54288",
    "cellulare": "",
    "email": "info@kyrimai.gr",
    "web": "https://www.kyrimai.gr",
    "note": "Mani",
    "mappa": "Mani, Peliponnese, Gerolimenas, GR"
  },
  {
    "nome": "La Conca del Sogno",
    "indirizzo": "Via San Marciano 9",
    "citta": "Nerano",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "luogo": "Nerano (NA)",
    "tel": "+39 081 8081036",
    "telefono": "+39 081 8081036",
    "cellulare": "",
    "email": "info@concadelsogno.it",
    "web": "https://www.concadelsogno.it",
    "note": "🌳🌅 🏖♥️️",
    "mappa": "Via San Marciano 9, Nerano, NA"
  },
  {
    "nome": "La Darbia",
    "indirizzo": "Via per Miasino",
    "citta": "Orta San Giulio",
    "provincia": "NO",
    "prov": "NO",
    "regione": "Piemonte",
    "luogo": "Orta San Giulio (NO)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 389 3113813",
    "email": "info@ladarbia.com",
    "web": "https://ladarbia.com",
    "note": "🌅 🌳♥️",
    "mappa": "Via per Miasino, Orta San Giulio, NO"
  },
  {
    "nome": "La Foresteria Wine Resort",
    "indirizzo": "Contrada Passo di Gurra, Ex S.S. 115 s.p. 79, Km 91",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529986",
    "telefono": "+39 0925 529986",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Contrada Passo di Gurra, Ex S.S. 115 s.p. 79, Km 91, Menfi, AG"
  },
  {
    "nome": "La Francesca",
    "indirizzo": "Via Gloria Bortolotti De Poli 8",
    "citta": "Scario",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Scario (SA)",
    "tel": "+39 0974 986068",
    "telefono": "+39 0974 986068",
    "cellulare": "+39 335 5986434",
    "email": "info@lafrancescasud.it",
    "web": "https://lafrancescascario.it",
    "note": "Ospitalità in vecchie case 🌳 🌅 🏖♥️️",
    "mappa": "Via Gloria Bortolotti De Poli 8, Scario, SA"
  },
  {
    "nome": "La Gioiosa",
    "indirizzo": "Via Manie 55",
    "citta": "Finale Ligure",
    "provincia": "SV",
    "prov": "SV",
    "regione": "Liguria",
    "luogo": "Finale Ligure (SV)",
    "tel": "+39 019 601306",
    "telefono": "+39 019 601306",
    "cellulare": "",
    "email": "",
    "web": "https://www.lagioiosahotel.it",
    "note": "6,5 km dall'uscita A10 Finale Ligure 🌳🌅",
    "mappa": "Via Manie 55, Finale Ligure, SV"
  },
  {
    "nome": "La Lampara",
    "indirizzo": "Via Tramonti 4",
    "citta": "Campiglia",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "luogo": "Campiglia (SP)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 342 0736590",
    "email": "liviacerliani96@gmail.com",
    "web": "https://lalamparacampiglia.com/pages/camere",
    "note": "🌅 ♥️",
    "mappa": "Via Tramonti 4, Campiglia, SP"
  },
  {
    "nome": "La Parisienne",
    "indirizzo": "Via Enrico Mattei, 28",
    "citta": "Senigallia",
    "provincia": "AN",
    "prov": "AN",
    "regione": "Marche",
    "luogo": "Senigallia (AN)",
    "tel": "+39 071 6610052",
    "telefono": "+39 071 6610052",
    "cellulare": "",
    "email": "",
    "web": "https://www.bblaparisienne.it/",
    "note": "",
    "mappa": "Via Enrico Mattei, 28, Senigallia, AN"
  },
  {
    "nome": "La Quinta Miraflores",
    "indirizzo": "844 Avenida 28 de julio",
    "citta": "Miraflores, Lima",
    "provincia": "PE",
    "prov": "PE",
    "regione": "Perù",
    "luogo": "Miraflores, Lima (PE)",
    "tel": "+51 995 938 000",
    "telefono": "+51 995 938 000",
    "cellulare": "+51 995 680 854",
    "email": "b.hotel@quintamiraflores.com",
    "web": "https://www.quintamiraflores.com",
    "note": "",
    "mappa": "844 Avenida 28 de julio, Miraflores, Lima, PE"
  },
  {
    "nome": "La Raia",
    "indirizzo": "Località Lomellina 26",
    "citta": "Gavi",
    "provincia": "AL",
    "prov": "AL",
    "regione": "Piemonte",
    "luogo": "Gavi (AL)",
    "tel": "+39 0143 642860",
    "telefono": "+39 0143 642860",
    "cellulare": "",
    "email": "locanda@la-raia.it",
    "web": "https://www.la-raia.it/it",
    "note": "Albergo di charme sui colli di Gavi 🌳 ♥️",
    "mappa": "Località Lomellina 26, Gavi, AL"
  },
  {
    "nome": "La Roccia",
    "indirizzo": "Via Litoranea Tricase",
    "citta": "Castro",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "luogo": "Castro (LE)",
    "tel": "+39 0836 979013",
    "telefono": "+39 0836 979013",
    "cellulare": "",
    "email": "info@larocciahotel.it",
    "web": "https://larocciahotel.it",
    "note": "🌳 🌅 🏖️",
    "mappa": "Via Litoranea Tricase, Castro, LE"
  },
  {
    "nome": "La Soglina",
    "indirizzo": "Via Carnella 6",
    "citta": "Soglio",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Svizzera",
    "luogo": "Soglio (GR)",
    "tel": "+41 81 822 16 08",
    "telefono": "+41 81 822 16 08",
    "cellulare": "",
    "email": "info@lasoglina.ch",
    "web": "https://www.lasoglina.ch",
    "note": "Vista sulla Val Bregaglia 🌳🌄 ♥️",
    "mappa": "Via Carnella 6, Soglio, GR"
  },
  {
    "nome": "La Sommità Relais",
    "indirizzo": "Via Scipione Petrarolo 7",
    "citta": "Ostuni",
    "provincia": "BR",
    "prov": "BR",
    "regione": "Puglia",
    "luogo": "Ostuni (BR)",
    "tel": "+39 0831 305925",
    "telefono": "+39 0831 305925",
    "cellulare": "",
    "email": "info@lasommita.it",
    "web": "https://www.lasommita.it",
    "note": "🌄♥️",
    "mappa": "Via Scipione Petrarolo 7, Ostuni, BR"
  },
  {
    "nome": "Le Bristol",
    "indirizzo": "112 rue Di Faubourg Saint-Honoré",
    "citta": "Paris",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Paris (F)",
    "tel": "+33 1 53 43 43 00",
    "telefono": "+33 1 53 43 43 00",
    "cellulare": "",
    "email": "reservations.lebristolparis@oetkerhotels.com",
    "web": "https://www.oetkerhotels.com/hotels/le-bristol-paris/",
    "note": "👑 ♥️",
    "mappa": "112 rue Di Faubourg Saint-Honoré, Paris, F"
  },
  {
    "nome": "Le Comptoir du Relais Saint Germain",
    "indirizzo": "9, Carrefour de l'Odéon",
    "citta": "Paris",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Paris (F)",
    "tel": "+33 1 44 27 07 97",
    "telefono": "+33 1 44 27 07 97",
    "cellulare": "",
    "email": "hotel@le-relais-saint-germain.com",
    "web": "https://www.hotel-paris-relais-saint-germain.com/en/",
    "note": "",
    "mappa": "9, Carrefour de l'Odéon, Paris, F"
  },
  {
    "nome": "Les Trois Rois",
    "indirizzo": "Blumenrain 8",
    "citta": "Basel",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Svizzera",
    "luogo": "Basel (BS)",
    "tel": "+41 79 756 36 24",
    "telefono": "+41 79 756 36 24",
    "cellulare": "",
    "email": "asseghid.dinberu spirithotels.com",
    "web": "https://www.lestroisrois.com",
    "note": "👑 ♥️",
    "mappa": "Blumenrain 8, Basel, BS"
  },
  {
    "nome": "Locanda dell'Angelo",
    "indirizzo": "Viale XXV Aprile 60",
    "citta": "Ameglia",
    "provincia": "SP",
    "prov": "SP",
    "regione": "Liguria",
    "luogo": "Ameglia (SP)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 351 6204850",
    "email": "info@paracucchilocanda.it",
    "web": "https://www.paracucchilocanda.it",
    "note": "",
    "mappa": "Viale XXV Aprile 60, Ameglia, SP"
  },
  {
    "nome": "Locanda Romantica Pucci",
    "indirizzo": "Piazza Cavour 1",
    "citta": "Bagnoregio",
    "provincia": "VT",
    "prov": "VT",
    "regione": "Lazio",
    "luogo": "Bagnoregio (VT)",
    "tel": "+39 0761 792121",
    "telefono": "+39 0761 792121",
    "cellulare": "+39 339 2320735",
    "email": "info@hotelromanticapucci.it",
    "web": "https://www.hotelromanticapucci.it",
    "note": "♥️",
    "mappa": "Piazza Cavour 1, Bagnoregio, VT"
  },
  {
    "nome": "L’Agnata",
    "indirizzo": "Località l’Agnata San Bachisio",
    "citta": "Tempio Pausania",
    "provincia": "SS",
    "prov": "SS",
    "regione": "Sardegna",
    "luogo": "Tempio Pausania (SS)",
    "tel": "+39 079 671384",
    "telefono": "+39 079 671384",
    "cellulare": "",
    "email": "info@agnata.com",
    "web": "https://www.agnata.com",
    "note": "Stazzu gallurese immerso nella natura 🌳♥️",
    "mappa": "Località l’Agnata San Bachisio, Tempio Pausania, SS"
  },
  {
    "nome": "L’Albereta",
    "indirizzo": "Via Vittorio Emanuele 40",
    "citta": "Erbusco",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Lombardia",
    "luogo": "Erbusco (BS)",
    "tel": "+390307760550",
    "telefono": "+390307760550",
    "cellulare": "",
    "email": "info@albereta.it",
    "web": "https://www.albereta.it",
    "note": "Immerso in un parco 🌳♥️",
    "mappa": "Via Vittorio Emanuele 40, Erbusco, BS"
  },
  {
    "nome": "Maison La Minervetta",
    "indirizzo": "Via Capo 25",
    "citta": "Sorrento",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "luogo": "Sorrento (NA)",
    "tel": "+39 081 8774455",
    "telefono": "+39 081 8774455",
    "cellulare": "",
    "email": "info@laminervetta.com",
    "web": "https://www.laminervetta.com",
    "note": "🌄 🌅 ♥️",
    "mappa": "Via Capo 25, Sorrento, NA"
  },
  {
    "nome": "Mandarin Oriental Hyde Park",
    "indirizzo": "66 Knightsbridge",
    "citta": "London",
    "provincia": "GB",
    "prov": "GB",
    "regione": "Inghilterra",
    "luogo": "London (GB)",
    "tel": "+44 (0) 20 7235 2000",
    "telefono": "+44 (0) 20 7235 2000",
    "cellulare": "",
    "email": "molon-reservations@mohg.com",
    "web": "https://www.mandarinoriental.com/en/london/hyde-park/stay",
    "note": "Vista su Hyde Park 👑 🌳♥️",
    "mappa": "66 Knightsbridge, London, GB"
  },
  {
    "nome": "Mandarin Oriental Lago di Como",
    "indirizzo": "Via Enrico Caronti 69",
    "citta": "Blevio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "luogo": "Blevio (CO)",
    "tel": "+39 031 32511",
    "telefono": "+39 031 32511",
    "cellulare": "",
    "email": "",
    "web": "https://www.mandarinoriental.com/lake-como/blevio/luxur",
    "note": "🌳 🌅 🏖️",
    "mappa": "Via Enrico Caronti 69, Blevio, CO"
  },
  {
    "nome": "Mandarin Oriental Ritz",
    "indirizzo": "Plaza de la Lealtad 5",
    "citta": "Madrid",
    "provincia": "M",
    "prov": "M",
    "regione": "Spagna",
    "luogo": "Madrid (M)",
    "tel": "+34 91 7016888",
    "telefono": "+34 91 7016888",
    "cellulare": "",
    "email": "mrmad-reservations@mohg.com",
    "web": "https://www.mandarinoriental.com/en/madrid/hotel-ritz",
    "note": "👑 ♥️",
    "mappa": "Plaza de la Lealtad 5, Madrid, M"
  },
  {
    "nome": "Marulivo",
    "indirizzo": "Via Castello",
    "citta": "Pisciotta",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Pisciotta (SA)",
    "tel": "0974973792",
    "telefono": "0974973792",
    "cellulare": "",
    "email": "",
    "web": "https://www.marulivohotel.it",
    "note": "🌅",
    "mappa": "Via Castello, Pisciotta, SA"
  },
  {
    "nome": "Mezzatorre",
    "indirizzo": "Via Mezzatorre 23",
    "citta": "Ischia",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "luogo": "Ischia (NA)",
    "tel": "+39 081 986111",
    "telefono": "+39 081 986111",
    "cellulare": "",
    "email": "reservations@pellicanohotels.com",
    "web": "https://www.pellicanohotels.com/en/hotels/mezzatorre-hotel-e-thermal-spa/",
    "note": "🌳 🌅 🏖️",
    "mappa": "Via Mezzatorre 23, Ischia, NA"
  },
  {
    "nome": "Miralago",
    "indirizzo": "Miralago 10",
    "citta": "Miralago",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Svizzera",
    "luogo": "Miralago (GR)",
    "tel": "+41 81 839 20 00",
    "telefono": "+41 81 839 20 00",
    "cellulare": "",
    "email": "info@albergomiralago.ch",
    "web": "https://www.albergomiralago.ch",
    "note": "🌳 🌅",
    "mappa": "Miralago 10, Miralago, GR"
  },
  {
    "nome": "Mont Cervin Palace",
    "indirizzo": "Bahnhofstrasse 31",
    "citta": "Zermatt",
    "provincia": "VS",
    "prov": "VS",
    "regione": "Svizzera",
    "luogo": "Zermatt (VS)",
    "tel": "+41 27 966 88 88",
    "telefono": "+41 27 966 88 88",
    "cellulare": "",
    "email": "a.gartmann@seilerhotels.ch",
    "web": "https://www.montcervin.ch",
    "note": "⛰️ 🌳♥️",
    "mappa": "Bahnhofstrasse 31, Zermatt, VS"
  },
  {
    "nome": "Mosella Suite",
    "indirizzo": "Via San Felice 3",
    "citta": "Sottomarina di Chioggia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "luogo": "Sottomarina di Chioggia (VE)",
    "tel": "+39 041 0986095",
    "telefono": "+39 041 0986095",
    "cellulare": "",
    "email": "info@mosellasuitehotel.it",
    "web": "https://www.mosellasuitehotel.it",
    "note": "🌅",
    "mappa": "Via San Felice 3, Sottomarina di Chioggia, VE"
  },
  {
    "nome": "Palazzo Jannuzzi",
    "indirizzo": "Vico San Aniello 39",
    "citta": "Sorrento",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "luogo": "Sorrento (NA)",
    "tel": "(+39) 081 8772862",
    "telefono": "(+39) 081 8772862",
    "cellulare": "",
    "email": "info@palazzojannuzzi.com",
    "web": "https://www.palazzojannuzzi.com",
    "note": "",
    "mappa": "Vico San Aniello 39, Sorrento, NA"
  },
  {
    "nome": "Palazzo Planeta",
    "indirizzo": "Via Principe di Belmonte 68",
    "citta": "Palermo",
    "provincia": "PA",
    "prov": "PA",
    "regione": "Sicilia",
    "luogo": "Palermo (PA)",
    "tel": "+39 091 7330940",
    "telefono": "+39 091 7330940",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Via Principe di Belmonte 68, Palermo, PA"
  },
  {
    "nome": "Pardini's Hermitage",
    "indirizzo": "Cala degli Alberi",
    "citta": "Isola del Giglio",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Toscana",
    "luogo": "Isola del Giglio (GR)",
    "tel": "+39 0564 809034",
    "telefono": "+39 0564 809034",
    "cellulare": "+39 348 8131868",
    "email": "info@hermit.it",
    "web": "https://www.hermit.it",
    "note": "🌳 🌅 🏖️",
    "mappa": "Cala degli Alberi, Isola del Giglio, GR"
  },
  {
    "nome": "Park Villa Grazioli",
    "indirizzo": "Via Umberto Pavoni 19",
    "citta": "Grottaferrata",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "luogo": "Grottaferrata (RM)",
    "tel": "+3906945400",
    "telefono": "+3906945400",
    "cellulare": "",
    "email": "info@villa-grazioli.it",
    "web": "https://www.villa-grazioli.it",
    "note": "🌳♥️",
    "mappa": "Via Umberto Pavoni 19, Grottaferrata, RM"
  },
  {
    "nome": "Patria Palace",
    "indirizzo": "Piazzetta Gabriele Riccardi",
    "citta": "Lecce",
    "provincia": "LE",
    "prov": "LE",
    "regione": "Puglia",
    "luogo": "Lecce (LE)",
    "tel": "+39 0832 245111",
    "telefono": "+39 0832 245111",
    "cellulare": "",
    "email": "info@patriapalace.com",
    "web": "https://patriapalace.com",
    "note": "♥️",
    "mappa": "Piazzetta Gabriele Riccardi, Lecce, LE"
  },
  {
    "nome": "Pensione Tranchina",
    "indirizzo": "Via Armando Diaz 7",
    "citta": "Scopello",
    "provincia": "TP",
    "prov": "TP",
    "regione": "Sicilia",
    "luogo": "Scopello (TP)",
    "tel": "+39 0924 541099",
    "telefono": "+39 0924 541099",
    "cellulare": "",
    "email": "pensione.tranchina@gmail.com",
    "web": "https://www.pensionetranchina.com",
    "note": "",
    "mappa": "Via Armando Diaz 7, Scopello, TP"
  },
  {
    "nome": "Pippo’s Resort",
    "indirizzo": "Via Becarino 37",
    "citta": "Poppi",
    "provincia": "AR",
    "prov": "AR",
    "regione": "Toscana",
    "luogo": "Poppi (AR)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 335 6761257",
    "email": "ale@pipposlittleresort.com",
    "web": "https://www.pipposlittleresort.com",
    "note": "🌳♥️",
    "mappa": "Via Becarino 37, Poppi, AR"
  },
  {
    "nome": "Pirgos Mavromichali",
    "indirizzo": "",
    "citta": "Limeni Laconia",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Grecia",
    "luogo": "Limeni Laconia (GR)",
    "tel": "+30 27330 51042",
    "telefono": "+30 27330 51042",
    "cellulare": "+30 697 3757499",
    "email": "info@pirgosmavromichali.gr",
    "web": "https://www.pirgosmavromichali.gr/en",
    "note": "🌅",
    "mappa": "Limeni Laconia, GR"
  },
  {
    "nome": "Planeta Country House",
    "indirizzo": "Strada Provinciale 50,51",
    "citta": "Menfi",
    "provincia": "AG",
    "prov": "AG",
    "regione": "Sicilia",
    "luogo": "Menfi (AG)",
    "tel": "+39 0925 529988",
    "telefono": "+39 0925 529988",
    "cellulare": "",
    "email": "reservation@planeta.it",
    "web": "https://www.planetaestate.it/it/",
    "note": "Ospitalità nelle proprietà dell’azienda vinicola Planeta ♥️",
    "mappa": "Strada Provinciale 50,51 , Menfi, AG"
  },
  {
    "nome": "Principe di Savoia",
    "indirizzo": "Piazza della Repubblica 17",
    "citta": "Milano",
    "provincia": "MI",
    "prov": "MI",
    "regione": "Lombardia",
    "luogo": "Milano (MI)",
    "tel": "+39 02 62301",
    "telefono": "+39 02 62301",
    "cellulare": "",
    "email": "club10.HPS@dorchestercollection.com",
    "web": "https://www.hotelprincipedisavoia.com/contattaci-hotel-p",
    "note": "👑",
    "mappa": "Piazza della Repubblica 17, Milano, MI"
  },
  {
    "nome": "Principe Forte dei Marmi",
    "indirizzo": "Viale Ammiraglio Morin 67",
    "citta": "Forte dei Marmi",
    "provincia": "LU",
    "prov": "LU",
    "regione": "Toscana",
    "luogo": "Forte dei Marmi (LU)",
    "tel": "+39 0584 783636",
    "telefono": "+39 0584 783636",
    "cellulare": "",
    "email": "info@principefortedeimarmi.com",
    "web": "https://principefortedeimarmi.com/it",
    "note": "🌅 🏖️",
    "mappa": "Viale Ammiraglio Morin 67, Forte dei Marmi, LU"
  },
  {
    "nome": "Pà Khraizar",
    "indirizzo": "Frazione Lateis 5",
    "citta": "Sauris",
    "provincia": "UD",
    "prov": "UD",
    "regione": "Friuli-Venezia Giulia",
    "luogo": "Sauris (UD)",
    "tel": "+39 0433 86165",
    "telefono": "+39 0433 86165",
    "cellulare": "",
    "email": "info@pa-krhaizar.it",
    "web": "https://pa-krhaizar.it",
    "note": "⛰️🌳♥️",
    "mappa": "Frazione Lateis 5, Sauris, UD"
  },
  {
    "nome": "Raphaël",
    "indirizzo": "Largo Febo 2",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "luogo": "Roma (RM)",
    "tel": "+39 06 682831",
    "telefono": "+39 06 682831",
    "cellulare": "",
    "email": "rev@raphaelhotel.com",
    "web": "https://www.raphaelhotel.com",
    "note": "Viata sulla città ♥️",
    "mappa": "Largo Febo 2, Roma, RM"
  },
  {
    "nome": "Rector",
    "indirizzo": "Paseo Rector Esperabé 10",
    "citta": "Salamanca",
    "provincia": "ES",
    "prov": "ES",
    "regione": "Spagna",
    "luogo": "Salamanca (ES)",
    "tel": "+34 923 218 482",
    "telefono": "+34 923 218 482",
    "cellulare": "",
    "email": "info@hotelrector.com",
    "web": "https://www.hotelrector.com",
    "note": "♥️",
    "mappa": "Paseo Rector Esperabé 10, Salamanca, ES"
  },
  {
    "nome": "Relais Castello di Morcote",
    "indirizzo": "Portich de Sura",
    "citta": "Vico Morcote",
    "provincia": "TI",
    "prov": "TI",
    "regione": "Svizzera",
    "luogo": "Vico Morcote (TI)",
    "tel": "+41 91 980 22 52",
    "telefono": "+41 91 980 22 52",
    "cellulare": "",
    "email": "relais@castellodimorcote.ch",
    "web": "https://www.relaiscastellodimorcote.ch",
    "note": "♥️🌳",
    "mappa": "Portich de Sura, Vico Morcote, TI"
  },
  {
    "nome": "Relais Maso di Villa",
    "indirizzo": "Via Col di Guarda 15",
    "citta": "Susegana",
    "provincia": "TV",
    "prov": "TV",
    "regione": "Veneto",
    "luogo": "Susegana (TV)",
    "tel": "+39 0438 841414",
    "telefono": "+39 0438 841414",
    "cellulare": "",
    "email": "info@masodivilla.it",
    "web": "https://www.masodivilla.it/it/",
    "note": "♥️🌳",
    "mappa": "Via Col di Guarda 15, Susegana, TV"
  },
  {
    "nome": "Relais San Vigilio",
    "indirizzo": "Via al Castello 7",
    "citta": "Bergamo Alta",
    "provincia": "BG",
    "prov": "BG",
    "regione": "Lombardia",
    "luogo": "Bergamo Alta (BG)",
    "tel": "+39 035 2650987",
    "telefono": "+39 035 2650987",
    "cellulare": "",
    "email": "info@relaissanvigilio.it",
    "web": "https://www.relaissanvigilio.it",
    "note": "♥️🌳",
    "mappa": "Via al Castello 7, Bergamo Alta, BG"
  },
  {
    "nome": "Relais Villa d'Amelia",
    "indirizzo": "Località Manera 1",
    "citta": "Benevello",
    "provincia": "CN",
    "prov": "CN",
    "regione": "Piemonte",
    "luogo": "Benevello (CN)",
    "tel": "+39 0173 529225",
    "telefono": "+39 0173 529225",
    "cellulare": "",
    "email": "info@villadamelia.com",
    "web": "https://www.villadamelia.com",
    "note": "",
    "mappa": "Località Manera 1, Benevello, CN"
  },
  {
    "nome": "Residenza Scaravelli",
    "indirizzo": "Portici Broletto 22",
    "citta": "Mantova",
    "provincia": "MN",
    "prov": "MN",
    "regione": "Lombardia",
    "luogo": "Mantova (MN)",
    "tel": "+39 0376 226161",
    "telefono": "+39 0376 226161",
    "cellulare": "+39 393 3556479",
    "email": "residenza@scaravelli.it",
    "web": "https://www.scaravelli.it/residenza",
    "note": "Nel centro storico",
    "mappa": "Portici Broletto 22, Mantova, MN"
  },
  {
    "nome": "Retici Balzi",
    "indirizzo": "Via Panoramica 2",
    "citta": "Poggiridenti",
    "provincia": "SO",
    "prov": "SO",
    "regione": "Lombardia",
    "luogo": "Poggiridenti (SO)",
    "tel": "+39 0342 382092",
    "telefono": "+39 0342 382092",
    "cellulare": "",
    "email": "info@reticibalzi.it",
    "web": "https://www.reticibalzi.it",
    "note": "",
    "mappa": "Via Panoramica 2, Poggiridenti, SO"
  },
  {
    "nome": "Rocco Forte Hotels",
    "indirizzo": "Via del Babuino 9",
    "citta": "Roma",
    "provincia": "RM",
    "prov": "RM",
    "regione": "Lazio",
    "luogo": "Roma (RM)",
    "tel": "+39 06 328881",
    "telefono": "+39 06 328881",
    "cellulare": "",
    "email": "reservations.derussie@roccofortehotels.com",
    "web": "https://www.roccofortehotels.com/it/hotels-and-resorts/hotel-de-russie/",
    "note": "👑 ♥️",
    "mappa": "Via del Babuino 9, Roma, RM"
  },
  {
    "nome": "Romeo",
    "indirizzo": "Via Cristoforo Colombo 45",
    "citta": "Napoli",
    "provincia": "NA",
    "prov": "NA",
    "regione": "Campania",
    "luogo": "Napoli (NA)",
    "tel": "+39 081 0175001",
    "telefono": "+39 081 0175001",
    "cellulare": "",
    "email": "welcome.na@thrromeocollection.com",
    "web": "https://www.romeohotel.com/it/romeo-napoli/",
    "note": "Albergo con un design contemporaneo 🌅♥️",
    "mappa": "Via Cristoforo Colombo 45, Napoli, NA"
  },
  {
    "nome": "Rovereto",
    "indirizzo": "Corso Rosmini 82/D",
    "citta": "Rovereto",
    "provincia": "TN",
    "prov": "TN",
    "regione": "Trentino-Alto Adige",
    "luogo": "Rovereto (TN)",
    "tel": "+39 0464 435222",
    "telefono": "+39 0464 435222",
    "cellulare": "+39 335 5215815",
    "email": "",
    "web": "https://www.hotelrovereto.it",
    "note": "",
    "mappa": "Corso Rosmini 82/D, Rovereto, TN"
  },
  {
    "nome": "Sacher",
    "indirizzo": "Philharmonikerstraße 4",
    "citta": "Wien",
    "provincia": "W",
    "prov": "W",
    "regione": "Austria",
    "luogo": "Wien (W)",
    "tel": "+43 1 514 560",
    "telefono": "+43 1 514 560",
    "cellulare": "",
    "email": "wien@sacher.com",
    "web": "https://www.sacher.com",
    "note": "👑 ♥️",
    "mappa": "Philharmonikerstraße 4, Wien, W"
  },
  {
    "nome": "Salsomaggiore",
    "indirizzo": "Largo Roma 3",
    "citta": "Salsomaggiore Terme",
    "provincia": "PR",
    "prov": "PR",
    "regione": "Emilia-Romagna",
    "luogo": "Salsomaggiore Terme (PR)",
    "tel": "+39 0524 582311",
    "telefono": "+39 0524 582311",
    "cellulare": "",
    "email": "",
    "web": "https://www.chgroup.eu/grand-hotel-salsomaggiore/?utm_source=microsoft&utm_medium=cpc&utm_campaign=[FM]_Search_Brand_it_GHS",
    "note": "",
    "mappa": "Largo Roma 3, Salsomaggiore Terme, PR"
  },
  {
    "nome": "San Pietro",
    "indirizzo": "Via Laurito 2",
    "citta": "Positano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Positano (SA)",
    "tel": "+39 089 812080",
    "telefono": "+39 089 812080",
    "cellulare": "",
    "email": "reservations@ilsanpietro.it",
    "web": "https://www.ilsanpietro.com/it/",
    "note": "👑 🌳 🌅 🏖️ ♥️",
    "mappa": "Via Laurito 2, Positano, SA"
  },
  {
    "nome": "San Rocco",
    "indirizzo": "Via Gippini 11",
    "citta": "Orta San Giulio",
    "provincia": "NO",
    "prov": "NO",
    "regione": "Piemonte",
    "luogo": "Orta San Giulio (NO)",
    "tel": "+39 0322 911977",
    "telefono": "+39 0322 911977",
    "cellulare": "",
    "email": "info@hotelsanrocco.it",
    "web": "https://www.hotelsanrocco.it",
    "note": "🌅 🏖️",
    "mappa": "Via Gippini 11, Orta San Giulio, NO"
  },
  {
    "nome": "St. Regis Venezia",
    "indirizzo": "San Marco 2159",
    "citta": "Venezia",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "luogo": "Venezia (VE)",
    "tel": "+39 041 2400001",
    "telefono": "+39 041 2400001",
    "cellulare": "",
    "email": "",
    "web": "https://www.marriott.com/en-us/hotels/vcexr-the-st-regis-venice/overview/",
    "note": "Vista sul Canal Grande 🌅 ♥️",
    "mappa": "San Marco 2159, Venezia, VE"
  },
  {
    "nome": "Stella Maris",
    "indirizzo": "Punta Chiappa",
    "citta": "Camogli",
    "provincia": "GE",
    "prov": "GE",
    "regione": "Liguria",
    "luogo": "Camogli (GE)",
    "tel": "+39 0185 770285",
    "telefono": "+39 0185 770285",
    "cellulare": "",
    "email": "info@stellamaris.cc",
    "web": "https://www.stellamaris.cc",
    "note": "🌳🌅♥️",
    "mappa": "Punta Chiappa, Camogli, GE"
  },
  {
    "nome": "Tainaron Blue Retreat",
    "indirizzo": "Mani, Peliponnese",
    "citta": "Vathia",
    "provincia": "GR",
    "prov": "GR",
    "regione": "Grecia",
    "luogo": "Vathia (GR)",
    "tel": "+30 2108080049",
    "telefono": "+30 2108080049",
    "cellulare": "+30 6973007006",
    "email": "hide@tainaronblue.com",
    "web": "https://www.tainaronblue.com",
    "note": "Mani",
    "mappa": "Mani, Peliponnese, Vathia, GR"
  },
  {
    "nome": "The Lowell",
    "indirizzo": "28 East 63rd Street",
    "citta": "New York",
    "provincia": "NY",
    "prov": "NY",
    "regione": "Stati Uniti",
    "luogo": "New York (NY)",
    "tel": "+1 (212) 605-6812",
    "telefono": "+1 (212) 605-6812",
    "cellulare": "",
    "email": "abuchanan@lowellhotel.com",
    "web": "https://LowellHotel.com",
    "note": "",
    "mappa": "28 East 63rd Street, New York, NY"
  },
  {
    "nome": "The Sherry Netherland",
    "indirizzo": "781 Fifth Avenue",
    "citta": "New York",
    "provincia": "NY",
    "prov": "NY",
    "regione": "Stati Uniti",
    "luogo": "New York (NY)",
    "tel": "+1 (212) 355-2800",
    "telefono": "+1 (212) 355-2800",
    "cellulare": "",
    "email": "jacosta@sherrynetherland.com",
    "web": "https://www.sherrynetherland.com",
    "note": "🌄 ♥️",
    "mappa": "781 Fifth Avenue, New York, NY"
  },
  {
    "nome": "Tivoli Palazzo Gaddi",
    "indirizzo": "Via del Giglio 9",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "luogo": "Firenze (FI)",
    "tel": "+39 331 2947089",
    "telefono": "+39 331 2947089",
    "cellulare": "",
    "email": "info@terraerestaurant.it",
    "web": "https://www.terraerestaurant.it",
    "note": "",
    "mappa": "Via del Giglio 9, Firenze, FI"
  },
  {
    "nome": "Tonnara di Scopello",
    "indirizzo": "Largo Tonnara",
    "citta": "Scopello",
    "provincia": "TP",
    "prov": "TP",
    "regione": "Sicilia",
    "luogo": "Scopello (TP)",
    "tel": "+39 0924 1866101",
    "telefono": "+39 0924 1866101",
    "cellulare": "",
    "email": "booking@tonnaradiscopello.it",
    "web": "https://www.tonnaradiscopello.it",
    "note": "🌳 🌅 🏖️",
    "mappa": "Largo Tonnara, Scopello, TP"
  },
  {
    "nome": "Villa Abbazia",
    "indirizzo": "Via Martiri della Libertà 8",
    "citta": "Follina",
    "provincia": "TV",
    "prov": "TV",
    "regione": "Veneto",
    "luogo": "Follina (TV)",
    "tel": "+39 0438 971277",
    "telefono": "+39 0438 971277",
    "cellulare": "",
    "email": "info@hotelabbazia.it",
    "web": "https://www.hotelabbazia.com/it/",
    "note": "🌳♥️",
    "mappa": "Via Martiri della Libertà 8, Follina, TV"
  },
  {
    "nome": "Villa Castagnola",
    "indirizzo": "Via Pico 9",
    "citta": "Lugano",
    "provincia": "TI",
    "prov": "TI",
    "regione": "Svizzera",
    "luogo": "Lugano (TI)",
    "tel": "+41 91 9732555",
    "telefono": "+41 91 9732555",
    "cellulare": "",
    "email": "info@villacastagnola.com",
    "web": "https://www.villacastagnola.com",
    "note": "🌄 🌳 ♥️",
    "mappa": "Via Pico 9, Lugano, TI"
  },
  {
    "nome": "Villa Cicchi",
    "indirizzo": "Via Salaria Superiore 137",
    "citta": "Abbazia di Rosara",
    "provincia": "AP",
    "prov": "AP",
    "regione": "Marche",
    "luogo": "Abbazia di Rosara (AP)",
    "tel": "",
    "telefono": "",
    "cellulare": "+39 320 5764799",
    "email": "mariaelenacicchi@gmail.com",
    "web": "https://www.villacicchi.it",
    "note": "Residenza di campagna 🌳♥️",
    "mappa": "Via Salaria Superiore 137, Abbazia di Rosara, AP"
  },
  {
    "nome": "Villa Cora",
    "indirizzo": "Viale Machiavelli 18",
    "citta": "Firenze",
    "provincia": "FI",
    "prov": "FI",
    "regione": "Toscana",
    "luogo": "Firenze (FI)",
    "tel": "+39 055 228790",
    "telefono": "+39 055 228790",
    "cellulare": "+39 331 6619155",
    "email": "info@villacora.it",
    "web": "https://www.villacora.it",
    "note": "Sontuosa residenza, vista sulla città, 🌳♥️",
    "mappa": "Viale Machiavelli 18, Firenze, FI"
  },
  {
    "nome": "Villa Cortine Palace",
    "indirizzo": "Viale C. Gennari 2",
    "citta": "Sirmione",
    "provincia": "BS",
    "prov": "BS",
    "regione": "Lombardia",
    "luogo": "Sirmione (BS)",
    "tel": "+39 030 9905890",
    "telefono": "+39 030 9905890",
    "cellulare": "+39 335 8394499",
    "email": "roberto.cappelletto@hotelvillacorti",
    "web": "https://www.hotelvillacortine.com",
    "note": "Sontuosa residenza in un parco, 🌳♥️",
    "mappa": "Viale C. Gennari 2, Sirmione, BS"
  },
  {
    "nome": "Villa d’Este",
    "indirizzo": "Via Regina 40",
    "citta": "Cernobbio",
    "provincia": "CO",
    "prov": "CO",
    "regione": "Lombardia",
    "luogo": "Cernobbio (CO)",
    "tel": "+39 031 3481",
    "telefono": "+39 031 3481",
    "cellulare": "",
    "email": "info@villadeste.it",
    "web": "https://www.villadeste.com/it/",
    "note": "👑 🌅♥️",
    "mappa": "Via Regina 40, Cernobbio, CO"
  },
  {
    "nome": "Villa Franceschi",
    "indirizzo": "Via Don Giovanni Minzoni 27",
    "citta": "Mira",
    "provincia": "VE",
    "prov": "VE",
    "regione": "Veneto",
    "luogo": "Mira (VE)",
    "tel": "+39 0414266531",
    "telefono": "+39 0414266531",
    "cellulare": "",
    "email": "info@villafranceschi.com",
    "web": "https://www.villafranceschi.com",
    "note": "🌳♥️",
    "mappa": "Via Don Giovanni Minzoni 27, Mira, VE"
  },
  {
    "nome": "Villa Gallici",
    "indirizzo": "Avenue de la Violette",
    "citta": "Aix en Provence",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Aix en Provence (F)",
    "tel": "+33 (0) 4 42 32 92 3",
    "telefono": "+33 (0) 4 42 32 92 3",
    "cellulare": "",
    "email": "gallici@relaischateaux.fr",
    "web": "https://www.villagallici.com",
    "note": "♥️",
    "mappa": "Avenue de la Violette, Aix en Provence, F"
  },
  {
    "nome": "Villa Maria",
    "indirizzo": "Contrada Pretaro",
    "citta": "Francavilla al Mare",
    "provincia": "CH",
    "prov": "CH",
    "regione": "Abruzzo",
    "luogo": "Francavilla al Mare (CH)",
    "tel": "+39 085 450051",
    "telefono": "+39 085 450051",
    "cellulare": "",
    "email": "info@hvillamaria.it",
    "web": "https://hvillamaria.it",
    "note": "Vista mare 🌳♥️",
    "mappa": "Contrada Pretaro, Francavilla al Mare, CH"
  },
  {
    "nome": "Villa Santa Barbara",
    "indirizzo": "Via Federico Giunchi",
    "citta": "San Luca",
    "provincia": "PG",
    "prov": "PG",
    "regione": "Umbria",
    "luogo": "San Luca (PG)",
    "tel": "+39 0742 399402",
    "telefono": "+39 0742 399402",
    "cellulare": "",
    "email": "info@hotelvillasantabarbara.com",
    "web": "https://www.hotelvillasantabarbara.com",
    "note": "Residenza di campagna tra i vigneti ⛰️ 🌳♥️",
    "mappa": "Via Federico Giunchi, San Luca, PG"
  },
  {
    "nome": "Villa Treville",
    "indirizzo": "Via Arienzo 30",
    "citta": "Positano",
    "provincia": "SA",
    "prov": "SA",
    "regione": "Campania",
    "luogo": "Positano (SA)",
    "tel": "+39 089 8122401",
    "telefono": "+39 089 8122401",
    "cellulare": "+39 320 7197850",
    "email": "direttore@villatreville.it",
    "web": "https://www.villatreville.it",
    "note": "🌳 🌅 🏖️",
    "mappa": "Via Arienzo 30, Positano, SA"
  },
  {
    "nome": "Hôtel des Gouverneurs",
    "indirizzo": "3 bis Rue des Turquines",
    "citta": "Bastia",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Bastia (F)",
    "tel": "+33 4 95 47 10 10",
    "telefono": "+33 4 95 47 10 10",
    "cellulare": "",
    "email": "",
    "web": "https://www.hoteldesgouverneurs.fr",
    "note": "Boutique hotel nella Cittadella, vista sul Vieux Port 🌄 ♥️",
    "mappa": "3 bis Rue des Turquines, Bastia, F"
  },
  {
    "nome": "Dominique Colonna",
    "indirizzo": "Vallée de la Restonica",
    "citta": "Corte",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Corte (F)",
    "tel": "",
    "telefono": "",
    "cellulare": "",
    "email": "",
    "web": "",
    "note": "Terrazza sul fiume Tavignano, vicino all'università ⛰️",
    "mappa": "Vallée de la Restonica, 20250 Corte, F"
  },
  {
    "nome": "Domaine de Murtoli",
    "indirizzo": "Vallée de l'Ortolo",
    "citta": "Sartène",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Sartène (F)",
    "tel": "+33 4 95 71 69 24",
    "telefono": "+33 4 95 71 69 24",
    "cellulare": "",
    "email": "villas@murtoli.com",
    "web": "https://www.murtoli.com",
    "note": "2.500 ettari, ovili di pastori restaurati, spiaggia privata 🌳 🌅 ♥️",
    "mappa": "Vallée de l'Ortolo, Sartène, F"
  },
  {
    "nome": "Grand Hôtel de Cala Rossa",
    "indirizzo": "Route de Cala Rossa",
    "citta": "Lecci",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Lecci (F)",
    "tel": "+33 4 95 71 61 51",
    "telefono": "+33 4 95 71 61 51",
    "cellulare": "",
    "email": "",
    "web": "https://www.hotel-calarossa.com",
    "note": "A conduzione familiare, sulla spiaggia 🌅 🏖️ ♥️",
    "mappa": "Route de Cala Rossa, Lecci, F"
  },
  {
    "nome": "Domaine Le Mouflon d'Or",
    "indirizzo": "Pian di Santo",
    "citta": "Zonza",
    "provincia": "F",
    "prov": "F",
    "regione": "Francia",
    "luogo": "Zonza (F)",
    "tel": "+33 4 95 78 72 72",
    "telefono": "+33 4 95 78 72 72",
    "cellulare": "",
    "email": "info@lemouflondor.com",
    "web": "https://www.lemouflondor.com",
    "note": "Dimora di inizio Novecento fra cedri del Libano, 1 Chiave Michelin ⛰️ ♥️ 👑",
    "mappa": "Pian di Santo, Zonza, F"
  },
  {
    "nome": "Fior di Farine",
    "indirizzo": "Via Roma 108",
    "citta": "La Morra",
    "provincia": "CN",
    "prov": "CN",
    "regione": "Piemonte",
    "luogo": "La Morra (CN)",
    "tel": "+39 0173 50118",
    "telefono": "+39 0173 50118",
    "cellulare": "",
    "email": "info@ilmulinosobrino.it",
    "web": "https://www.fiordifarine.com",
    "note": "B&B legato al Mulino Sobrino, mugnai dal 1945, farine macinate in casa 🌄 ♥️",
    "mappa": "Via Roma 108, La Morra, CN"
  },
  {
    "nome": "La Moresca Maison de Charme",
    "indirizzo": "Via Dandolo 63",
    "citta": "Marina di Ragusa",
    "provincia": "RG",
    "prov": "RG",
    "regione": "Sicilia",
    "luogo": "Marina di Ragusa (RG)",
    "tel": "+39 0932 239495",
    "telefono": "+39 0932 239495",
    "cellulare": "",
    "email": "",
    "web": "https://www.lamorescahotel.it",
    "note": "Palazzo liberty di primo Novecento, 15 camere, 200 m dal mare ♥️ 🌄",
    "mappa": "Via Dandolo 63, Marina di Ragusa, RG"
  },
  {
    "nome": "Castello Tafuri",
    "indirizzo": "Via Tonnara 1",
    "citta": "Portopalo di Capo Passero",
    "provincia": "SR",
    "prov": "SR",
    "regione": "Sicilia",
    "luogo": "Portopalo di Capo Passero (SR)",
    "tel": "+39 0931 844111",
    "telefono": "+39 0931 844111",
    "cellulare": "",
    "email": "",
    "web": "https://www.castellotafuri.it",
    "note": "Residenza storica del 1935 accanto alla vecchia tonnara, spiaggia privata 🌅 ♥️",
    "mappa": "Via Tonnara 1, Portopalo di Capo Passero, SR"
  },
  {
    "nome": "Dimora Caiammari",
    "indirizzo": "Via Daniele Impellizzeri 6",
    "citta": "Siracusa",
    "provincia": "SR",
    "prov": "SR",
    "regione": "Sicilia",
    "luogo": "Siracusa (SR)",
    "tel": "+39 0931 721217",
    "telefono": "+39 0931 721217",
    "cellulare": "",
    "email": "info@caiammari.it",
    "web": "https://www.caiammari.it",
    "note": "Villa nobiliare del Seicento in giardino botanico storico, vicino al Plemmirio 🌄 🌳",
    "mappa": "Via Daniele Impellizzeri 6, Siracusa, SR"
  },
  {
    "nome": "Palazzo Salomone",
    "indirizzo": "Via Salomone 21",
    "citta": "Siracusa",
    "provincia": "SR",
    "prov": "SR",
    "regione": "Sicilia",
    "luogo": "Siracusa (SR)",
    "tel": "+39 0931 1815404",
    "telefono": "+39 0931 1815404",
    "cellulare": "+39 347 6193240",
    "email": "",
    "web": "https://www.palazzosalomone.com",
    "note": "Boutique hotel in Ortigia, ristorante interno Cortile Spirito Santo (1 Stella Michelin) ♥️ 👑",
    "mappa": "Via Salomone 21, Siracusa, SR"
  }
];
var HOTEL_PROVCITTA={
  "Abruzzo": [
    "AQ",
    "CH"
  ],
  "Austria": [
    "W"
  ],
  "Calabria": [
    "CS"
  ],
  "Campania": [
    "NA",
    "SA"
  ],
  "Cina": [
    "CN"
  ],
  "Emilia-Romagna": [
    "PR",
    "RN"
  ],
  "Francia": [
    "F"
  ],
  "Friuli-Venezia Giulia": [
    "TS",
    "UD"
  ],
  "Grecia": [
    "GR"
  ],
  "Inghilterra": [
    "GB"
  ],
  "Lazio": [
    "RM",
    "VT"
  ],
  "Liguria": [
    "GE",
    "IM",
    "SP",
    "SV"
  ],
  "Lombardia": [
    "BG",
    "BS",
    "CO",
    "LC",
    "MI",
    "MN",
    "SO"
  ],
  "Marche": [
    "AN",
    "AP"
  ],
  "Perù": [
    "PE"
  ],
  "Piemonte": [
    "AL",
    "CN",
    "NO",
    "TO"
  ],
  "Puglia": [
    "BR",
    "LE"
  ],
  "Russia": [
    "RU"
  ],
  "Sardegna": [
    "SS"
  ],
  "Sicilia": [
    "AG",
    "PA",
    "SR",
    "TP"
  ],
  "Spagna": [
    "ES",
    "M"
  ],
  "Stati Uniti": [
    "NY"
  ],
  "Svizzera": [
    "BS",
    "GE",
    "GR",
    "TI",
    "VS"
  ],
  "Tailandia": [
    "TH"
  ],
  "Toscana": [
    "AR",
    "FI",
    "GR",
    "LU",
    "SI"
  ],
  "Trentino-Alto Adige": [
    "BZ",
    "TN"
  ],
  "Umbria": [
    "PG"
  ],
  "Valle d'Aosta": [
    "AO"
  ],
  "Veneto": [
    "TV",
    "VE"
  ]
};
